# Resumable OTP Match Collection

This is a thin orchestration notebook. All collection and processing behavior lives in `otp_match_pipeline.py`; no timeline data is requested or used. Existing JSON files in `data/otp_raw_matches/` are treated as immutable cache entries.

In [22]:
import os
import importlib
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

import otp_match_pipeline as otp
otp = importlib.reload(otp)

load_dotenv(override=True)
RIOT_API_KEY = os.getenv('RIOT_API_KEY')
HEADERS = {'X-Riot-Token': RIOT_API_KEY} if RIOT_API_KEY else None

PROJECT_DIR = Path.cwd()
RAW_MATCH_DIR = PROJECT_DIR / 'data' / 'otp_raw_matches'
PROCESSED_DIR = PROJECT_DIR / 'data' / 'processed'
LEGACY_INDEX_PATH = PROCESSED_DIR / 'player_match_index_raw.csv'

print('Raw-match cache:', RAW_MATCH_DIR)
print('Riot API key available:', RIOT_API_KEY is not None)

Raw-match cache: /Users/minhho-hoang/Documents/riot_proj/riot-game-prediction/data/otp_raw_matches
Riot API key available: True

## Configuration

The default target is **5,000 distinct cached patch-16.19 Ranked Solo/Duo match JSONs referenced by the patch index**. Separately, each retained player-game uses exactly **50 completed Ranked Solo/Duo games before that match**, including older patches as needed. History IDs are requested in pages of 100. The notebook retrieves and caches the missing prior-game JSONs; this can require tens of thousands of extra API calls and take many hours. An interrupted run resumes from the cache and saved history index. Rows without all 50 usable prior games are excluded from the saved analysis data.

In [24]:
NUM_MASTER = 1000
NUM_GRANDMASTER = 350
NUM_CHALLENGER = 150
MATCHES_PER_PLAYER = 100  # Riot history page size; distinct from the OTP window
PRIOR_GAMES = 50  # Ranked Solo/Duo games strictly before each observation
MATCH_SELECTION_SEED = 1619  # Reproducible random order within each seed tier
TARGET_CACHED_PATCH_MATCHES = 2000  # Distinct cached 16.19 queue-420 matches in the patch index
TARGET_PATCH = "16.19"
PATCH_START_TIME = 1790164800  # 2026-09-23 12:00 UTC, before 16.19 went live on NA
PATCH_INDEX_STEM = "player_match_index_16_19"

# Enable only when you want to contact Riot and resume collection.
RUN_API_COLLECTION = True

DESIRED_SEED_COUNTS = {
    'master': NUM_MASTER,
    'grandmaster': NUM_GRANDMASTER,
    'challenger': NUM_CHALLENGER,
}

## Load and persist state

On first use, the legacy raw index is migrated: its selected players are preserved as Master seeds. The new index is deduplicated by `puuid + match_id` and written as CSV and Parquet.

In [25]:
seed_players = otp.load_seed_players(PROCESSED_DIR, LEGACY_INDEX_PATH)
seed_players = otp.save_seed_players(seed_players, PROCESSED_DIR)

historical_player_match_index = otp.load_player_match_index(
    PROCESSED_DIR, seed_players
)
historical_player_match_index = otp.save_player_match_index(
    historical_player_match_index, PROCESSED_DIR
)
patch_player_match_index = otp.load_player_match_index(
    PROCESSED_DIR, seed_players, PATCH_INDEX_STEM
)

print(f'Preserved seed players: {len(seed_players):,}')
print(f'Historical player-match relationships: {len(historical_player_match_index):,}')
print(f'Patch-16.19 player-match relationships: {len(patch_player_match_index):,}')

Preserved seed players: 3,000
Historical player-match relationships: 9,944
Patch-16.19 player-match relationships: 28,386

## Optional resumable API collection

The helper uses the NA1 Master, Grandmaster, and Challenger League-V4 endpoints for Ranked Solo/Duo and Match-V5 through Americas. Player-history IDs are saved in batches of 100 players; existing match JSONs remain in place. The download budget counts only **new, distinct, patch-16.19 Solo/Duo matches**, and only the patch-specific index is used when downloading. Candidate match IDs are shuffled within each tier so the old index does not take precedence over games newly discovered this weekend.

In [9]:
new_downloads_this_run = 0

if RUN_API_COLLECTION:
    if HEADERS is None:
        raise RuntimeError('Set RIOT_API_KEY in .env before enabling API collection.')

    seed_players = otp.extend_seed_players(
        seed_players, DESIRED_SEED_COUNTS, HEADERS
    )
    seed_players = otp.save_seed_players(seed_players, PROCESSED_DIR)

    patch_player_match_index = otp.append_match_histories(
        patch_player_match_index, seed_players, HEADERS, MATCHES_PER_PLAYER,
        start_time=PATCH_START_TIME,
        checkpoint_dir=PROCESSED_DIR, checkpoint_stem=PATCH_INDEX_STEM,
        checkpoint_every=100,
    )
    patch_player_match_index = otp.save_player_match_index(
        patch_player_match_index, PROCESSED_DIR, PATCH_INDEX_STEM
    )

    _, cached_patch_ids_before = otp.cached_patch_history_coverage(
        patch_player_match_index, RAW_MATCH_DIR, TARGET_PATCH, MATCHES_PER_PLAYER
    )
    downloads_remaining = max(0, TARGET_CACHED_PATCH_MATCHES - len(cached_patch_ids_before))
    print(f'Cached indexed {TARGET_PATCH} Solo/Duo matches: {len(cached_patch_ids_before):,}')
    print(f'Qualifying matches needed to reach {TARGET_CACHED_PATCH_MATCHES:,}: {downloads_remaining:,}')

    if downloads_remaining:
        _, _, new_downloads_this_run = otp.download_missing_matches(
            patch_player_match_index, RAW_MATCH_DIR, HEADERS,
            downloads_remaining, target_patch=TARGET_PATCH,
            selection_seed=MATCH_SELECTION_SEED,
        )
    else:
        print('The target for cached, indexed patch Solo/Duo matches is already complete.')
else:
    print('Cached-data mode: no Riot API calls were made.')

player_match_index = otp._normalise_index(
    pd.concat(
        [historical_player_match_index, patch_player_match_index],
        ignore_index=True,
    ),
    seed_players,
)

Master seeds retained: 2000
Grandmaster seeds retained: 700
Challenger seeds retained: 300
History page 0 skipped for seed 1/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/nqbLzjBKJ99ism-hPNRUDsxBA_V059cu_zUPnHiLS_Bh3KhRtBIo1cqoBzrRSq-zEU0MkBWr3o3uoA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 1/3000: 0 history IDs
History page 0 skipped for seed 2/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/0wanq1XDJV3BdiIPRHsEFxngU82mqcS7DJWWPWBHJgLscMrYHVPg-IV9DkNQghZUFAx3xD4Kk5GldA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 2/3000: 0 history IDs
History page 0 skipped for seed 3/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/REWYRKIsnDECu_JuOB_dy4UFsuceVaLpKrFO5H3wd7yTqCWrh9uNqH50ph3bEK-atn8B6frT3o6ctA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 3/3000: 0 history IDs
History page 0 skipped for seed 4/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/LCkN2fS5KQbgbXz3y9y7EUtU1k752T2hAIqqL9H7brACZFGG9eRujcb9U6SEWX2TI8Njs6coYc7YHQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 4/3000: 0 history IDs
History page 0 skipped for seed 5/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/EA1BQQcFBKFo748SJS1AmVsc0MSQb1SoUSXYD0U2d1C_1gneXYxaVAnjM2pWM6UDHvPbrTUOpGoYrw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 5/3000: 0 history IDs
History page 0 skipped for seed 6/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/-wL2JE9u3WJvgBRtMHRi5q_0gHk497NAD4WQr2M7XMFDOq4fHELcSOT86vJL-5n7MC4vIDmKeD6d0A/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 6/3000: 0 history IDs
History page 0 skipped for seed 7/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/pewiUYBm3_jmTqZ7fOQTFb5TAltoCUCZTgskwh4v9o1XHU7XvudF-nxvVbtJKQW6rA9POX9NeGQL5g/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 7/3000: 0 history IDs
History page 0 skipped for seed 8/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/28jv-JVXOLSHGkK_C_DuUcsxsdv0RJPtHZ1yX3d5O1g5T9yeLgyDIJJGa4F0YOEBycDU_zo-mv2dNw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 8/3000: 0 history IDs
History page 0 skipped for seed 9/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/Rp2gn8qjnXHmZE_DPX8o1-USc0k-FNFX-GHTzr9NC67bODiSgvn2Xb3bhRGDrk9w2lS2EkWjHyg4pg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 9/3000: 0 history IDs
History page 0 skipped for seed 10/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/GTtvNWHSckQSxkcbT9IeTskW937_wjoljcRIvcbFsRhjb-XaOCPvYjMyDK-TmGM1E1lH3HiyyGOllA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 10/3000: 0 history IDs
History page 0 skipped for seed 11/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/61zxQ2mjo3GczD5N6TAEItY5IesBiTk-jQhjVWVDAiXHWFO9T011ZefAMIaiAHb7mb15u58Kglx35A/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 11/3000: 0 history IDs
History page 0 skipped for seed 12/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/7sEjosHl6x367yZWnxYVSlkC1d5eOE5HeAjmtr9r40Y06XsJP-gZMZTClBoggNSAo_ZgEpYSYpTjwg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 12/3000: 0 history IDs
History page 0 skipped for seed 13/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/ToJzMBS3nrB_0-q0kX5OyoTSxLL7ZgKHjpkO3fQiyMhEvBg9Dn4POQjuiI6_ildhFpFu8O5XzegYZw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 13/3000: 0 history IDs
History page 0 skipped for seed 14/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/jFSU8TXal_sBzGiz8V5LGlKaNyl9G5u3jWbsVE9Sr0K0dLM8dCvokGUSQeyI9K5e7mhwiGoXhz6rnQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 14/3000: 0 history IDs
History page 0 skipped for seed 15/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/0swQuwCh9vIrHLMBw-4V5fqUJ9wRrgjytjfXKUZ3z1utFawa1664X9ZVLX3WauzSPUHKBsssMlyHFw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 15/3000: 0 history IDs
History page 0 skipped for seed 16/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/h23-tnBUnDykiGRUav2hkW23x8ZG94RXwleVty64KrjMWX3duITp8pjhCCdA5iQprpLCFeEo4LUeMA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 16/3000: 0 history IDs
History page 0 skipped for seed 17/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/P8ks-Hn6RzQAvjtW0goMCTgrY6ErjDs94pi78gtjm0Gc40ClnHJrxBBwga_Cl5mK-7H6KgOpZJ2Kcg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 17/3000: 0 history IDs
History page 0 skipped for seed 18/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/--FJUTNd1d7l_i6FhjCChnK1ITJ1lSPuk_7U42LlyKR-2O1okm5Ret-ndgkpaegVGHKckvVwuPiatw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 18/3000: 0 history IDs
History page 0 skipped for seed 19/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/e70KQOjSORBfwSLt-XvjC0w8dZyOet0R2uaFDMKh7peeNv_jmxJoLf6SBY31lueb-p1GJQgXI8IQ-A/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 19/3000: 0 history IDs
History page 0 skipped for seed 20/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/umL1sveWU2gR-rm7cxzgba914x6hPDY0sVrHZxWdCoFV9dJPmOf_h5Ft_nZsFRh5RwBqajlpgxnqlw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 20/3000: 0 history IDs
History page 0 skipped for seed 21/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/UCnauZN8XRz62Hv9VjEJFNW6AF9eVGDTSXHOEW2NdjuyCP-x1Z7dSdxC1Q9p_jKC60nD68GKuOKeAA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 21/3000: 0 history IDs
History page 0 skipped for seed 22/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/HupoV4QLHZW9wYa2LPUySgU9uJBH2zcj1PiyAZRx_ClhoIzNnjbBmLeNzx9h1tdEWtWuimqUqHCv7Q/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 22/3000: 0 history IDs
History page 0 skipped for seed 23/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/_QQYyfQeMRQMh-fK5gbu12_7pInD3oZgWAntBu7wtFbvEygvue3GFEFgkcZrTjpandVOVS4dSiBQXQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 23/3000: 0 history IDs
History page 0 skipped for seed 24/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/SfMf2aeobC9TrIVUCJ4SSh9tDYAcdXputabWv40T7YiCU2K46uoq4-EVcTw8GF0lGdJccwEH-0OGYQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 24/3000: 0 history IDs
History page 0 skipped for seed 25/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/U4uik9xyxUQ93aIvJ5fcaT8Y-gk32zSR944UNwzz_MY-BTiD_j0WYrJ-TpNiZHK1x06AbxTx9qFatg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 25/3000: 0 history IDs
History page 0 skipped for seed 26/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/o769Yd1f6cOQmKc9bz-V5zr_ycmmIL8I34bX7EhUD0psegdb7IheDutThBiGw-V2oluHsdMdav-E7g/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 26/3000: 0 history IDs
History page 0 skipped for seed 27/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/Bc1h4Diutbn1ZYVwDrUggBo2j9XVjpOzqjIWrTNXz4Do_CYDouSJSLASOE7yOiGulPE7ZTKcmkqdbQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 27/3000: 0 history IDs
History page 0 skipped for seed 28/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/r1xVd7eyPgMiYRyUqE356LeDQuwfom28rDLjGHUNkDcHKpH-K8uaQJFOEOtYbVdRTFUkA6JxyvZqIQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 28/3000: 0 history IDs
History page 0 skipped for seed 29/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/Exegay_0EOSqoQqOoaFwo4gTnCSkcYEobNAc0rs_Ex3yLNX30MX1kWLjMeWtLtaq45YZ69AIL4YZPg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 29/3000: 0 history IDs
History page 0 skipped for seed 30/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/55g0YmTvgwhh0EXUusXjeRJMTZPLqp8wRZ_YLAED1-nx9dgN40DY7-oFixEXboqF45y9gv7MX-Ax8Q/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 30/3000: 0 history IDs
History page 0 skipped for seed 31/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/XYjCtHA-CEBVK3_dTpHOGAHX6vzfIE97SZBwT0Cm3svGfO4Tzl9GwYvP1RVdxFA1vwtIMLPSmGY94Q/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 31/3000: 0 history IDs
History page 0 skipped for seed 32/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/Ppm5R3jem_xRbN6ol0qaK55X4R-Nx2NtAISrJvNq9ETqe0hrDHOgTc1aVncmXskul8JFvsGkgxFfpg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 32/3000: 0 history IDs
History page 0 skipped for seed 33/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/i4snsNxLwumbQZdY0BKgBsldgvjqt5iyZ2uUt8WpU-fP6S2SZNhwaMhZGgwhjdojlxz9KCKI4l5AOg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 33/3000: 0 history IDs
History page 0 skipped for seed 34/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/hg9-01wRoOaWGhG06JMP7bJp39Xftp-ZCpfNu66BSPyKGV7wF7tWJzhFAeoO4uN4Z8lCvWOQKsaCDA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 34/3000: 0 history IDs
History page 0 skipped for seed 35/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/Ee3q4IPjmo_aG-QsBrFecG6Lpew2vKA5RcT6ckySgy5IPlU6BDHWxe5iIMoXl4anp87uLx3xB94bbg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 35/3000: 0 history IDs
History page 0 skipped for seed 36/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/Vb2ftVK0iDMVjrh0qmNJM0U-DrSgocA-RZfHGuPoPMfnS2iDgFCIVvWmh_VqhRJ4KagiAcq9iOZ4IA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 36/3000: 0 history IDs
History page 0 skipped for seed 37/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/-hzNoO54EDjdSm8IkM3CPP-pQ_XuixTnqj3LIRKRl8s-gMziHK7LACNWP1bHI-8siWttNn81L4-sQA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 37/3000: 0 history IDs
History page 0 skipped for seed 38/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/YeeaklDrV9AyHqNMbqMLepVip3oeZ7YL_SsGkiazFu9GCk3K20bOcSs6Ye4fdG0dzFPYuNvamNHltg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 38/3000: 0 history IDs
History page 0 skipped for seed 39/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/JS1nllU29hFj57cQCSaGzUgaJWg_nXYej0sPdiUxoC0WNfGta_ucjabH8WFOwoWj6DJl6aMnN11vQw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 39/3000: 0 history IDs
History page 0 skipped for seed 40/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/kY3AxLmq1RWsIl6XZdBttt3Gl0qikOJa7j-R-Qg9n2lwzlw_fj9ytSB7uwVoKeqZSuyBSN4ehPqVVA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 40/3000: 0 history IDs
History page 0 skipped for seed 41/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/9ocFMq9F7Ed-wInHN-GE-irzf3JhM3QnHHarHp-p-UzZye_KKDzPgFJI04lyPQ-xRMlsemqOwgWLNA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 41/3000: 0 history IDs
History page 0 skipped for seed 42/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/mYqMu6da_zI8AtwCowqIgG_kHQl1VtAUS-ENVFKKY5RVLzBJS0hITFgRKQ-SknnIWRprlXMCmwrFIA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 42/3000: 0 history IDs
History page 0 skipped for seed 43/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/7nfURKfTnDZ-spwhHft3k4rZg5gtU9Ee5MHyJ_lBMMm5sdVGRhwb8dHB4uLSZKc3_tErKyE33Kz7Kg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 43/3000: 0 history IDs
History page 0 skipped for seed 44/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/3s00lfrqCZ2XJAwBeJeCL4CXHqKEsNnE6eIrUFSeQybxALJPWzvR3vGieiGPgd3BRinn8KY8UDIbNA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 44/3000: 0 history IDs
History page 0 skipped for seed 45/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/6zitfigwStC6fxG8R-KCrgDttUDvX7RGArC59vQ7nuH1aKwg9YqqHjhXSzEeNOFGftWjc4vHFowCDQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 45/3000: 0 history IDs
History page 0 skipped for seed 46/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/EhaKiCDmpKt2aVuy0v7x4Pb2d4z04Vp0E2pKaJrHiUJPukJrmvWO_YkSQKZ6asZ4BemHPzpLL7fvVQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 46/3000: 0 history IDs
History page 0 skipped for seed 47/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/7CIw5BacJZj140DCKfZ-IwHDNsyax34twrWQiuJ3ybpxys6UYKfhAce1Uf3FJIe4l-AC1ThIvtrUsw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 47/3000: 0 history IDs
History page 0 skipped for seed 48/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/BQ_87oWlvLaq_kElPl7I8plYXDo15x4Bds8zv6mFj_X4lSm_M7zCTvXXeW-NM7uGSSnHMaqdBSwuvw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 48/3000: 0 history IDs
History page 0 skipped for seed 49/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/5Cdyhevlrit5gDsEPczojwh-77hHHj-iaf-Q_7-SAgJqpWT1pLDAd2WjeIlWkbD_6XCfkaHsqWrM_g/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 49/3000: 0 history IDs
History page 0 skipped for seed 50/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/HvrxCXo-tZIvJ5BV-fKH2yb_Bw-psBN7XsDsDJae77IuQQoun6eg3j7qTd-kJZyvVHgw__6zxddiBA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 50/3000: 0 history IDs
History page 0 skipped for seed 51/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/S4-Rf3eS6DyUauRhJtyE26X1r5S9TavVKMGLpZXsXY1kJALPsKekQHf0Y06blMQQaovr6YhCxteh1Q/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 51/3000: 0 history IDs
History page 0 skipped for seed 52/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/kudJsIqXivNykUUAsUsMxdBwMK5o7XJYraLtaqY7uKZ7ygeEE6R8NBEwJ2J0oslPD8oDqn1QQ_BCQQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 52/3000: 0 history IDs
History page 0 skipped for seed 53/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/VKGqykHeiaK8TG6hTGT9CucYOjB5y_mTfEg47lQ9dc1VxCcO4q9iBh1EelNQ3E52iFR2OmZViR-CsQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 53/3000: 0 history IDs
History page 0 skipped for seed 54/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/B5lsnOSGZBFFDgNRknOwtcxScfrPOTUDnepA8sayk4fp5hv2ijv60hiE91ajTamsA0QujHG2g7bC3A/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 54/3000: 0 history IDs
History page 0 skipped for seed 55/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/TdgWzZCqT1gh0jhab1IvVcj2TvN64wjmBH_jrYdvVGnTp7QgKEzusyLNd4OszfT_TPsYv7OFdgHpbA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 55/3000: 0 history IDs
History page 0 skipped for seed 56/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/QHpZmH74SdgUJsCDbSpUu8e_5Y0SAPoEPbb4tQYBlLusLwY-pbKKXtsDHBhPhz5ChKFLWEc3y5KB8A/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 56/3000: 0 history IDs
History page 0 skipped for seed 57/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/alxSXNtO7_5elc7Nbxaopmnt2ziVo98RAyzo1bYssqEH9x6ACHSlZDLxt7K2naMZWl0Q4b1AQ7vyHg/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 57/3000: 0 history IDs
History page 0 skipped for seed 58/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/27mNqIecQxaGSWhqv-HgJYwvbNvrQ9tNuROuBlTIcnqteuVtQO720_p3Y4t2_BhfCyhnfJsV4nMSmQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 58/3000: 0 history IDs
History page 0 skipped for seed 59/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/-PAURslsQt-YkgvZDuG4-lhj-LN1uYde1l3x0q9UqEqf_BhE_fQeVUqwPCJS8Z1zP9U5i64VIdDTVA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 59/3000: 0 history IDs
History page 0 skipped for seed 60/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/TSfaPmHGNjQW55GMBS4gPXOXRQvMGn60Xo2LEGsoJrHwfvOiQNB49L3Oa_bOO4PbacoOr_YAjdyRIw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 60/3000: 0 history IDs
History page 0 skipped for seed 61/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/w01Cx-1PUfWnonXFv7nEWJZaoZJa2KOdVb8XT5B2Nr3LWbLFyIAW5wZimtPDCcVC9Sx1L1b3OfLg7A/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 61/3000: 0 history IDs
History page 0 skipped for seed 62/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/bQHM7Y5ox3vCzHy9sG_2_kfRnxabVEQds2L3QXZj_3SyChExwsOGVNmiiozCj0s6K3aCVSISWtt8mQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 62/3000: 0 history IDs
History page 0 skipped for seed 63/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/RtAn1WYQxuh7XYzEQvL9LL4Pyrt4X-wcY37cTgBlyclc860aohPIS9pl8In9Bpyo9fXjYXyBKrA2EA/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 63/3000: 0 history IDs
History page 0 skipped for seed 64/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/CuKY7bDcvLbo_3kmUhWma7EYGZ22lpUecDjzCf4IPnZ-xzCzwYz2nJUBmDgnW3yqCZgmyXWm2Fh5HQ/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 64/3000: 0 history IDs
History page 0 skipped for seed 65/3000: 401 Client Error: Unauthorized for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/IVkTldcCT8z6gZpd-1H_XOoLjrg1k15WDQY0vdiAfQiSktMNB382Pjecsr8G7cWfCp0MJQaFsupnaw/ids?queue=420&start=0&count=100&startTime=1790164800
Seed 65/3000: 0 history IDs

KeyboardInterrupt:

In [26]:
# Snapshot every match ID we already knew about BEFORE today's collection.
old_match_ids = set(
    patch_player_match_index["match_id"].dropna().unique()
)

print(f"Old stored match IDs to exclude: {len(old_match_ids):,}")

# Start a fresh index for today's history pull.
fresh_patch_index = pd.DataFrame(
    columns=["puuid", "match_id", "seed_tier"]
)

# Ask Riot for the current patch-16.19 histories of our EXISTING 3,000 seeds.
fresh_patch_index = otp.append_match_histories(
    fresh_patch_index,
    seed_players,
    HEADERS,
    MATCHES_PER_PLAYER,
    start_time=PATCH_START_TIME,
)

# Remove every match that was already in our old saved index.
new_only_index = fresh_patch_index.loc[
    ~fresh_patch_index["match_id"].isin(old_match_ids)
].copy()

print(
    f"Fresh player-match relationships: {len(fresh_patch_index):,}"
)
print(
    f"NEW player-match relationships after excluding old IDs: "
    f"{len(new_only_index):,}"
)
print(
    f"Distinct NEW match IDs available: "
    f"{new_only_index['match_id'].nunique():,}"
)

Old stored match IDs to exclude: 10,201
Seed 1/3000: 17 history IDs
Seed 2/3000: 64 history IDs
Seed 3/3000: 5 history IDs
Seed 4/3000: 1 history IDs
Seed 5/3000: 18 history IDs
Seed 6/3000: 16 history IDs
Seed 7/3000: 19 history IDs
Seed 8/3000: 1 history IDs
Seed 9/3000: 0 history IDs
Seed 10/3000: 1 history IDs
Seed 11/3000: 3 history IDs
Seed 12/3000: 20 history IDs
Seed 13/3000: 79 history IDs
Seed 14/3000: 67 history IDs
Seed 15/3000: 56 history IDs
Seed 16/3000: 2 history IDs
Seed 17/3000: 11 history IDs
Seed 18/3000: 94 history IDs
Seed 19/3000: 61 history IDs
Seed 20/3000: 0 history IDs
Seed 21/3000: 0 history IDs
Seed 22/3000: 4 history IDs
Seed 23/3000: 21 history IDs
Seed 24/3000: 26 history IDs
Seed 25/3000: 3 history IDs
Seed 26/3000: 0 history IDs
Seed 27/3000: 3 history IDs
Seed 28/3000: 86 history IDs
Seed 29/3000: 9 history IDs
Seed 30/3000: 26 history IDs
Seed 31/3000: 4 history IDs
Seed 32/3000: 59 history IDs
Seed 33/3000: 5 history IDs
Seed 34/3000: 3 history IDs
Seed 35/3000: 8 history IDs
Seed 36/3000: 40 history IDs
Seed 37/3000: 4 history IDs
Seed 38/3000: 45 history IDs
Seed 39/3000: 8 history IDs
Seed 40/3000: 4 history IDs
Seed 41/3000: 30 history IDs
Seed 42/3000: 8 history IDs
Seed 43/3000: 65 history IDs
Seed 44/3000: 6 history IDs
Seed 45/3000: 12 history IDs
Seed 46/3000: 52 history IDs
Seed 47/3000: 7 history IDs
Seed 48/3000: 10 history IDs
Seed 49/3000: 14 history IDs
Seed 50/3000: 1 history IDs
Seed 51/3000: 15 history IDs
Seed 52/3000: 16 history IDs
Seed 53/3000: 16 history IDs
Seed 54/3000: 26 history IDs
Seed 55/3000: 42 history IDs
Seed 56/3000: 4 history IDs
Seed 57/3000: 7 history IDs
Seed 58/3000: 15 history IDs
Seed 59/3000: 41 history IDs
Seed 60/3000: 15 history IDs
Seed 61/3000: 9 history IDs
Seed 62/3000: 65 history IDs
Seed 63/3000: 55 history IDs
Seed 64/3000: 56 history IDs
Seed 65/3000: 15 history IDs
Seed 66/3000: 0 history IDs
Seed 67/3000: 0 history IDs
Seed 68/3000: 13 history IDs
Seed 69/3000: 6 history IDs
Seed 70/3000: 18 history IDs
Seed 71/3000: 20 history IDs
Seed 72/3000: 25 history IDs
Seed 73/3000: 20 history IDs
Seed 74/3000: 13 history IDs
Seed 75/3000: 14 history IDs
Seed 76/3000: 35 history IDs
Seed 77/3000: 0 history IDs
Seed 78/3000: 0 history IDs
Seed 79/3000: 5 history IDs
Seed 80/3000: 13 history IDs
Seed 81/3000: 5 history IDs
Seed 82/3000: 0 history IDs
Seed 83/3000: 34 history IDs
Seed 84/3000: 3 history IDs
Seed 85/3000: 7 history IDs
Seed 86/3000: 72 history IDs
Seed 87/3000: 0 history IDs
Seed 88/3000: 103 history IDs
Seed 89/3000: 20 history IDs
Seed 90/3000: 0 history IDs
Seed 91/3000: 14 history IDs
Seed 92/3000: 10 history IDs
Seed 93/3000: 50 history IDs
Seed 94/3000: 9 history IDs
Seed 95/3000: 0 history IDs
Seed 96/3000: 6 history IDs
Seed 97/3000: 48 history IDs
Seed 98/3000: 44 history IDs
Seed 99/3000: 0 history IDs
Seed 100/3000: 19 history IDs
Seed 101/3000: 40 history IDs
Seed 102/3000: 20 history IDs
Seed 103/3000: 2 history IDs
Seed 104/3000: 8 history IDs
Seed 105/3000: 6 history IDs
Seed 106/3000: 2 history IDs
Seed 107/3000: 13 history IDs
Seed 108/3000: 26 history IDs
Seed 109/3000: 38 history IDs
Seed 110/3000: 5 history IDs
Seed 111/3000: 44 history IDs
Seed 112/3000: 51 history IDs
Seed 113/3000: 119 history IDs
Seed 114/3000: 8 history IDs
Seed 115/3000: 35 history IDs
Seed 116/3000: 3 history IDs
Seed 117/3000: 20 history IDs
Seed 118/3000: 2 history IDs
Seed 119/3000: 0 history IDs
Seed 120/3000: 41 history IDs
Seed 121/3000: 22 history IDs
Seed 122/3000: 22 history IDs
Seed 123/3000: 23 history IDs
Seed 124/3000: 13 history IDs
Seed 125/3000: 0 history IDs
Seed 126/3000: 21 history IDs
Seed 127/3000: 45 history IDs
Seed 128/3000: 6 history IDs
Seed 129/3000: 4 history IDs
Seed 130/3000: 0 history IDs
Seed 131/3000: 0 history IDs
Seed 132/3000: 29 history IDs
Seed 133/3000: 106 history IDs
Seed 134/3000: 60 history IDs
Seed 135/3000: 35 history IDs
Seed 136/3000: 1 history IDs
Seed 137/3000: 8 history IDs
Seed 138/3000: 20 history IDs
Seed 139/3000: 0 history IDs
Seed 140/3000: 48 history IDs
Seed 141/3000: 17 history IDs
Seed 142/3000: 120 history IDs
Seed 143/3000: 23 history IDs
Seed 144/3000: 5 history IDs
Seed 145/3000: 10 history IDs
Seed 146/3000: 46 history IDs
Seed 147/3000: 24 history IDs
Seed 148/3000: 48 history IDs
Seed 149/3000: 0 history IDs
Seed 150/3000: 52 history IDs
Seed 151/3000: 14 history IDs
Seed 152/3000: 14 history IDs
Seed 153/3000: 8 history IDs
Seed 154/3000: 0 history IDs
Seed 155/3000: 11 history IDs
Seed 156/3000: 1 history IDs
Seed 157/3000: 6 history IDs
Seed 158/3000: 60 history IDs
Seed 159/3000: 32 history IDs
Seed 160/3000: 36 history IDs
Seed 161/3000: 2 history IDs
Seed 162/3000: 14 history IDs
Seed 163/3000: 29 history IDs
Seed 164/3000: 66 history IDs
Seed 165/3000: 19 history IDs
Seed 166/3000: 11 history IDs
Seed 167/3000: 101 history IDs
Seed 168/3000: 30 history IDs
Seed 169/3000: 7 history IDs
Seed 170/3000: 7 history IDs
Seed 171/3000: 9 history IDs
Seed 172/3000: 20 history IDs
Seed 173/3000: 3 history IDs
Seed 174/3000: 17 history IDs
Seed 175/3000: 10 history IDs
Seed 176/3000: 27 history IDs
Seed 177/3000: 6 history IDs
Seed 178/3000: 9 history IDs
Seed 179/3000: 23 history IDs
Seed 180/3000: 8 history IDs
Seed 181/3000: 24 history IDs
Seed 182/3000: 36 history IDs
Seed 183/3000: 85 history IDs
Seed 184/3000: 14 history IDs
Seed 185/3000: 3 history IDs
Seed 186/3000: 6 history IDs
Seed 187/3000: 57 history IDs
Seed 188/3000: 3 history IDs
Seed 189/3000: 36 history IDs
Seed 190/3000: 23 history IDs
Seed 191/3000: 74 history IDs
Seed 192/3000: 33 history IDs
Seed 193/3000: 12 history IDs
Seed 194/3000: 5 history IDs
Rate limited; waiting 101 seconds.
Seed 195/3000: 67 history IDs
Seed 196/3000: 15 history IDs
Seed 197/3000: 50 history IDs
Seed 198/3000: 9 history IDs
Seed 199/3000: 66 history IDs
Seed 200/3000: 21 history IDs
Seed 201/3000: 70 history IDs
Seed 202/3000: 41 history IDs
Seed 203/3000: 3 history IDs
Seed 204/3000: 11 history IDs
Seed 205/3000: 46 history IDs
Seed 206/3000: 11 history IDs
Seed 207/3000: 50 history IDs
Seed 208/3000: 2 history IDs
Seed 209/3000: 18 history IDs
Seed 210/3000: 5 history IDs
Seed 211/3000: 7 history IDs
Seed 212/3000: 26 history IDs
Seed 213/3000: 44 history IDs
Seed 214/3000: 28 history IDs
Seed 215/3000: 24 history IDs
Seed 216/3000: 56 history IDs
Seed 217/3000: 20 history IDs
Seed 218/3000: 16 history IDs
Seed 219/3000: 8 history IDs
Seed 220/3000: 6 history IDs
Seed 221/3000: 20 history IDs
Seed 222/3000: 43 history IDs
Seed 223/3000: 44 history IDs
Seed 224/3000: 37 history IDs
Seed 225/3000: 17 history IDs
Seed 226/3000: 69 history IDs
Seed 227/3000: 7 history IDs
Seed 228/3000: 20 history IDs
Seed 229/3000: 151 history IDs
Seed 230/3000: 28 history IDs
Seed 231/3000: 95 history IDs
Seed 232/3000: 89 history IDs
Seed 233/3000: 21 history IDs
Seed 234/3000: 129 history IDs
Seed 235/3000: 3 history IDs
Seed 236/3000: 26 history IDs
Seed 237/3000: 9 history IDs
Seed 238/3000: 13 history IDs
Seed 239/3000: 26 history IDs
Seed 240/3000: 30 history IDs
Seed 241/3000: 3 history IDs
Seed 242/3000: 5 history IDs
Seed 243/3000: 9 history IDs
Seed 244/3000: 32 history IDs
Seed 245/3000: 11 history IDs
Seed 246/3000: 16 history IDs
Seed 247/3000: 10 history IDs
Seed 248/3000: 6 history IDs
Seed 249/3000: 25 history IDs
Seed 250/3000: 17 history IDs
Seed 251/3000: 4 history IDs
Seed 252/3000: 15 history IDs
Seed 253/3000: 1 history IDs
Seed 254/3000: 0 history IDs
Seed 255/3000: 1 history IDs
Seed 256/3000: 4 history IDs
Seed 257/3000: 2 history IDs
Seed 258/3000: 25 history IDs
Seed 259/3000: 8 history IDs
Seed 260/3000: 23 history IDs
Seed 261/3000: 17 history IDs
Seed 262/3000: 45 history IDs
Seed 263/3000: 17 history IDs
Seed 264/3000: 46 history IDs
Seed 265/3000: 53 history IDs
Seed 266/3000: 58 history IDs
Seed 267/3000: 26 history IDs
Seed 268/3000: 4 history IDs
Seed 269/3000: 9 history IDs
Seed 270/3000: 0 history IDs
Seed 271/3000: 15 history IDs
Seed 272/3000: 9 history IDs
Seed 273/3000: 0 history IDs
Seed 274/3000: 77 history IDs
Seed 275/3000: 73 history IDs
Seed 276/3000: 8 history IDs
Seed 277/3000: 10 history IDs
Seed 278/3000: 15 history IDs
Seed 279/3000: 53 history IDs
Seed 280/3000: 4 history IDs
Seed 281/3000: 78 history IDs
Seed 282/3000: 28 history IDs
Seed 283/3000: 6 history IDs
Seed 284/3000: 56 history IDs
Seed 285/3000: 43 history IDs
Seed 286/3000: 30 history IDs
Seed 287/3000: 38 history IDs
Seed 288/3000: 20 history IDs
Seed 289/3000: 26 history IDs
Seed 290/3000: 29 history IDs
Seed 291/3000: 0 history IDs
Seed 292/3000: 53 history IDs
Rate limited; waiting 100 seconds.
Seed 293/3000: 18 history IDs
Seed 294/3000: 21 history IDs
Seed 295/3000: 6 history IDs
Seed 296/3000: 21 history IDs
Seed 297/3000: 22 history IDs
Seed 298/3000: 8 history IDs
Seed 299/3000: 82 history IDs
Seed 300/3000: 9 history IDs
Seed 301/3000: 9 history IDs
Seed 302/3000: 18 history IDs
Seed 303/3000: 47 history IDs
Seed 304/3000: 3 history IDs
Seed 305/3000: 41 history IDs
Seed 306/3000: 0 history IDs
Seed 307/3000: 27 history IDs
Seed 308/3000: 9 history IDs
Seed 309/3000: 26 history IDs
Seed 310/3000: 20 history IDs
Seed 311/3000: 13 history IDs
Seed 312/3000: 55 history IDs
Seed 313/3000: 4 history IDs
Seed 314/3000: 18 history IDs
Seed 315/3000: 24 history IDs
Seed 316/3000: 75 history IDs
Seed 317/3000: 4 history IDs
Seed 318/3000: 59 history IDs
Seed 319/3000: 9 history IDs
Seed 320/3000: 25 history IDs
Seed 321/3000: 8 history IDs
Seed 322/3000: 11 history IDs
Seed 323/3000: 83 history IDs
Seed 324/3000: 8 history IDs
Seed 325/3000: 18 history IDs
Seed 326/3000: 32 history IDs
Seed 327/3000: 13 history IDs
Seed 328/3000: 5 history IDs
Seed 329/3000: 29 history IDs
Seed 330/3000: 53 history IDs
Seed 331/3000: 18 history IDs
Seed 332/3000: 12 history IDs
Seed 333/3000: 69 history IDs
Seed 334/3000: 33 history IDs
Seed 335/3000: 93 history IDs
Seed 336/3000: 6 history IDs
Seed 337/3000: 49 history IDs
Seed 338/3000: 5 history IDs
Seed 339/3000: 35 history IDs
Seed 340/3000: 4 history IDs
Seed 341/3000: 0 history IDs
Seed 342/3000: 15 history IDs
Seed 343/3000: 18 history IDs
Seed 344/3000: 20 history IDs
Seed 345/3000: 19 history IDs
Seed 346/3000: 8 history IDs
Seed 347/3000: 15 history IDs
Seed 348/3000: 41 history IDs
Seed 349/3000: 31 history IDs
Seed 350/3000: 9 history IDs
Seed 351/3000: 20 history IDs
Seed 352/3000: 20 history IDs
Seed 353/3000: 23 history IDs
Seed 354/3000: 6 history IDs
Seed 355/3000: 0 history IDs
Seed 356/3000: 62 history IDs
Seed 357/3000: 39 history IDs
Seed 358/3000: 77 history IDs
Seed 359/3000: 15 history IDs
Seed 360/3000: 28 history IDs
Seed 361/3000: 10 history IDs
Seed 362/3000: 12 history IDs
Seed 363/3000: 0 history IDs
Seed 364/3000: 104 history IDs
Seed 365/3000: 32 history IDs
Seed 366/3000: 9 history IDs
Seed 367/3000: 29 history IDs
Seed 368/3000: 12 history IDs
Seed 369/3000: 77 history IDs
Seed 370/3000: 8 history IDs
Seed 371/3000: 14 history IDs
Seed 372/3000: 8 history IDs
Seed 373/3000: 33 history IDs
Seed 374/3000: 45 history IDs
Seed 375/3000: 25 history IDs
Seed 376/3000: 0 history IDs
Seed 377/3000: 0 history IDs
Seed 378/3000: 14 history IDs
Seed 379/3000: 13 history IDs
Seed 380/3000: 17 history IDs
Seed 381/3000: 13 history IDs
Seed 382/3000: 24 history IDs
Seed 383/3000: 4 history IDs
Seed 384/3000: 0 history IDs
Seed 385/3000: 18 history IDs
Seed 386/3000: 3 history IDs
Seed 387/3000: 77 history IDs
Seed 388/3000: 21 history IDs
Seed 389/3000: 16 history IDs
Seed 390/3000: 34 history IDs
Seed 391/3000: 44 history IDs
Rate limited; waiting 101 seconds.
Seed 392/3000: 15 history IDs
Seed 393/3000: 4 history IDs
Seed 394/3000: 0 history IDs
Seed 395/3000: 10 history IDs
Seed 396/3000: 30 history IDs
Seed 397/3000: 63 history IDs
Seed 398/3000: 12 history IDs
Seed 399/3000: 0 history IDs
Seed 400/3000: 2 history IDs
Seed 401/3000: 0 history IDs
Seed 402/3000: 37 history IDs
Seed 403/3000: 59 history IDs
Seed 404/3000: 15 history IDs
Seed 405/3000: 8 history IDs
Seed 406/3000: 7 history IDs
Seed 407/3000: 36 history IDs
Seed 408/3000: 35 history IDs
Seed 409/3000: 7 history IDs
Seed 410/3000: 16 history IDs
Seed 411/3000: 7 history IDs
Seed 412/3000: 6 history IDs
Seed 413/3000: 131 history IDs
Seed 414/3000: 8 history IDs
Seed 415/3000: 33 history IDs
Seed 416/3000: 4 history IDs
Seed 417/3000: 55 history IDs
Seed 418/3000: 63 history IDs
Seed 419/3000: 20 history IDs
Seed 420/3000: 3 history IDs
Seed 421/3000: 7 history IDs
Seed 422/3000: 30 history IDs
Seed 423/3000: 0 history IDs
Seed 424/3000: 28 history IDs
Seed 425/3000: 33 history IDs
Seed 426/3000: 10 history IDs
Seed 427/3000: 9 history IDs
Seed 428/3000: 12 history IDs
Seed 429/3000: 99 history IDs
Seed 430/3000: 7 history IDs
Seed 431/3000: 6 history IDs
Seed 432/3000: 15 history IDs
Seed 433/3000: 1 history IDs
Seed 434/3000: 10 history IDs
Seed 435/3000: 0 history IDs
Seed 436/3000: 8 history IDs
Seed 437/3000: 4 history IDs
Seed 438/3000: 11 history IDs
Seed 439/3000: 9 history IDs
Seed 440/3000: 26 history IDs
Seed 441/3000: 0 history IDs
Seed 442/3000: 39 history IDs
Seed 443/3000: 18 history IDs
Seed 444/3000: 58 history IDs
Seed 445/3000: 7 history IDs
Seed 446/3000: 6 history IDs
Seed 447/3000: 3 history IDs
Seed 448/3000: 0 history IDs
Seed 449/3000: 27 history IDs
Seed 450/3000: 0 history IDs
Seed 451/3000: 33 history IDs
Seed 452/3000: 6 history IDs
Seed 453/3000: 17 history IDs
Seed 454/3000: 33 history IDs
Seed 455/3000: 20 history IDs
Seed 456/3000: 102 history IDs
Seed 457/3000: 4 history IDs
Seed 458/3000: 31 history IDs
Seed 459/3000: 85 history IDs
Seed 460/3000: 63 history IDs
Seed 461/3000: 30 history IDs
Seed 462/3000: 13 history IDs
Seed 463/3000: 53 history IDs
Seed 464/3000: 13 history IDs
Seed 465/3000: 10 history IDs
Seed 466/3000: 41 history IDs
Seed 467/3000: 135 history IDs
Seed 468/3000: 6 history IDs
Seed 469/3000: 10 history IDs
Seed 470/3000: 1 history IDs
Seed 471/3000: 18 history IDs
Seed 472/3000: 14 history IDs
Seed 473/3000: 33 history IDs
Seed 474/3000: 86 history IDs
Seed 475/3000: 64 history IDs
Seed 476/3000: 14 history IDs
Seed 477/3000: 19 history IDs
Seed 478/3000: 16 history IDs
Seed 479/3000: 13 history IDs
Seed 480/3000: 19 history IDs
Seed 481/3000: 7 history IDs
Seed 482/3000: 7 history IDs
Seed 483/3000: 39 history IDs
Seed 484/3000: 9 history IDs
Seed 485/3000: 31 history IDs
Seed 486/3000: 53 history IDs
Seed 487/3000: 8 history IDs
Seed 488/3000: 28 history IDs
Rate limited; waiting 99 seconds.
Seed 489/3000: 66 history IDs
Seed 490/3000: 7 history IDs
Seed 491/3000: 44 history IDs
Seed 492/3000: 43 history IDs
Seed 493/3000: 10 history IDs
Seed 494/3000: 52 history IDs
Seed 495/3000: 29 history IDs
Seed 496/3000: 15 history IDs
Seed 497/3000: 28 history IDs
Seed 498/3000: 8 history IDs
Seed 499/3000: 142 history IDs
Seed 500/3000: 4 history IDs
Seed 501/3000: 16 history IDs
Seed 502/3000: 0 history IDs
Seed 503/3000: 17 history IDs
Seed 504/3000: 5 history IDs
Seed 505/3000: 31 history IDs
Seed 506/3000: 17 history IDs
Seed 507/3000: 42 history IDs
Seed 508/3000: 0 history IDs
Seed 509/3000: 5 history IDs
Seed 510/3000: 3 history IDs
Seed 511/3000: 22 history IDs
Seed 512/3000: 101 history IDs
Seed 513/3000: 11 history IDs
Seed 514/3000: 0 history IDs
Seed 515/3000: 15 history IDs
Seed 516/3000: 6 history IDs
Seed 517/3000: 20 history IDs
Seed 518/3000: 9 history IDs
Seed 519/3000: 98 history IDs
Seed 520/3000: 0 history IDs
Seed 521/3000: 9 history IDs
Seed 522/3000: 20 history IDs
Seed 523/3000: 0 history IDs
Seed 524/3000: 9 history IDs
Seed 525/3000: 10 history IDs
Seed 526/3000: 8 history IDs
Seed 527/3000: 0 history IDs
Seed 528/3000: 1 history IDs
Seed 529/3000: 23 history IDs
Seed 530/3000: 2 history IDs
Seed 531/3000: 19 history IDs
Seed 532/3000: 5 history IDs
Seed 533/3000: 10 history IDs
Seed 534/3000: 0 history IDs
Seed 535/3000: 28 history IDs
Seed 536/3000: 7 history IDs
Seed 537/3000: 49 history IDs
Seed 538/3000: 14 history IDs
Seed 539/3000: 12 history IDs
Seed 540/3000: 7 history IDs
Seed 541/3000: 47 history IDs
Seed 542/3000: 11 history IDs
Seed 543/3000: 55 history IDs
Seed 544/3000: 0 history IDs
Seed 545/3000: 11 history IDs
Seed 546/3000: 18 history IDs
Seed 547/3000: 34 history IDs
Seed 548/3000: 20 history IDs
Seed 549/3000: 19 history IDs
Seed 550/3000: 62 history IDs
Seed 551/3000: 4 history IDs
Seed 552/3000: 0 history IDs
Seed 553/3000: 39 history IDs
Seed 554/3000: 9 history IDs
Seed 555/3000: 18 history IDs
Seed 556/3000: 8 history IDs
Seed 557/3000: 30 history IDs
Seed 558/3000: 7 history IDs
Seed 559/3000: 36 history IDs
Seed 560/3000: 10 history IDs
Seed 561/3000: 10 history IDs
Seed 562/3000: 17 history IDs
Seed 563/3000: 0 history IDs
Seed 564/3000: 64 history IDs
Seed 565/3000: 44 history IDs
Seed 566/3000: 17 history IDs
Seed 567/3000: 21 history IDs
Seed 568/3000: 0 history IDs
Seed 569/3000: 11 history IDs
Seed 570/3000: 10 history IDs
Seed 571/3000: 43 history IDs
Seed 572/3000: 20 history IDs
Seed 573/3000: 48 history IDs
Seed 574/3000: 0 history IDs
Seed 575/3000: 9 history IDs
Seed 576/3000: 8 history IDs
Seed 577/3000: 8 history IDs
Seed 578/3000: 5 history IDs
Seed 579/3000: 7 history IDs
Seed 580/3000: 9 history IDs
Seed 581/3000: 4 history IDs
Seed 582/3000: 10 history IDs
Seed 583/3000: 46 history IDs
Seed 584/3000: 48 history IDs
Seed 585/3000: 63 history IDs
Seed 586/3000: 8 history IDs
Rate limited; waiting 101 seconds.
Seed 587/3000: 15 history IDs
Seed 588/3000: 12 history IDs
Seed 589/3000: 27 history IDs
Seed 590/3000: 28 history IDs
Seed 591/3000: 26 history IDs
Seed 592/3000: 0 history IDs
Seed 593/3000: 24 history IDs
Seed 594/3000: 5 history IDs
Seed 595/3000: 53 history IDs
Seed 596/3000: 9 history IDs
Seed 597/3000: 3 history IDs
Seed 598/3000: 51 history IDs
Seed 599/3000: 21 history IDs
Seed 600/3000: 9 history IDs
Seed 601/3000: 5 history IDs
Seed 602/3000: 22 history IDs
Seed 603/3000: 0 history IDs
Seed 604/3000: 8 history IDs
Seed 605/3000: 9 history IDs
Seed 606/3000: 8 history IDs
Seed 607/3000: 15 history IDs
Seed 608/3000: 148 history IDs
Seed 609/3000: 40 history IDs
Seed 610/3000: 0 history IDs
Seed 611/3000: 7 history IDs
Seed 612/3000: 3 history IDs
Seed 613/3000: 44 history IDs
Seed 614/3000: 53 history IDs
Seed 615/3000: 2 history IDs
Seed 616/3000: 35 history IDs
Seed 617/3000: 34 history IDs
Seed 618/3000: 4 history IDs
Seed 619/3000: 22 history IDs
Seed 620/3000: 8 history IDs
Seed 621/3000: 3 history IDs
Seed 622/3000: 7 history IDs
Seed 623/3000: 11 history IDs
Seed 624/3000: 5 history IDs
Seed 625/3000: 36 history IDs
Seed 626/3000: 5 history IDs
Seed 627/3000: 0 history IDs
Seed 628/3000: 32 history IDs
Seed 629/3000: 40 history IDs
Seed 630/3000: 5 history IDs
Seed 631/3000: 13 history IDs
Seed 632/3000: 50 history IDs
Seed 633/3000: 7 history IDs
Seed 634/3000: 4 history IDs
Seed 635/3000: 8 history IDs
Seed 636/3000: 34 history IDs
Seed 637/3000: 0 history IDs
Seed 638/3000: 0 history IDs
Seed 639/3000: 26 history IDs
Seed 640/3000: 58 history IDs
Seed 641/3000: 10 history IDs
Seed 642/3000: 38 history IDs
Seed 643/3000: 32 history IDs
Seed 644/3000: 8 history IDs
Seed 645/3000: 15 history IDs
Seed 646/3000: 5 history IDs
Seed 647/3000: 9 history IDs
Seed 648/3000: 25 history IDs
Seed 649/3000: 14 history IDs
Seed 650/3000: 11 history IDs
Seed 651/3000: 38 history IDs
Seed 652/3000: 6 history IDs
Seed 653/3000: 6 history IDs
Seed 654/3000: 11 history IDs
Seed 655/3000: 60 history IDs
Seed 656/3000: 15 history IDs
Seed 657/3000: 14 history IDs
Seed 658/3000: 22 history IDs
Seed 659/3000: 32 history IDs
Seed 660/3000: 13 history IDs
Seed 661/3000: 0 history IDs
Seed 662/3000: 8 history IDs
Seed 663/3000: 13 history IDs
Seed 664/3000: 0 history IDs
Seed 665/3000: 9 history IDs
Seed 666/3000: 55 history IDs
Seed 667/3000: 6 history IDs
Seed 668/3000: 77 history IDs
Seed 669/3000: 44 history IDs
Seed 670/3000: 0 history IDs
Seed 671/3000: 30 history IDs

In [28]:
_, _, downloaded = otp.download_missing_matches(
    new_only_index,
    RAW_MATCH_DIR,
    HEADERS,
    max_new_downloads=2000,
    target_patch=TARGET_PATCH,
    selection_seed=MATCH_SELECTION_SEED,
)

print(f"New qualifying matches downloaded: {downloaded:,}")

Cached matches found: 24
Match IDs requested: 18,130
New matches remaining: 18,106
New qualifying downloads this run: 1/2000 (NA1_5651855316)
New qualifying downloads this run: 2/2000 (NA1_5652787828)
New qualifying downloads this run: 3/2000 (NA1_5650842349)
New qualifying downloads this run: 4/2000 (NA1_5652553814)
New qualifying downloads this run: 5/2000 (NA1_5650339301)
New qualifying downloads this run: 6/2000 (NA1_5652523814)
New qualifying downloads this run: 7/2000 (NA1_5652119910)
New qualifying downloads this run: 8/2000 (NA1_5651700311)
New qualifying downloads this run: 9/2000 (NA1_5650493451)
New qualifying downloads this run: 10/2000 (NA1_5650193139)
New qualifying downloads this run: 11/2000 (NA1_5651938140)
New qualifying downloads this run: 12/2000 (NA1_5651121458)
New qualifying downloads this run: 13/2000 (NA1_5651041118)
New qualifying downloads this run: 14/2000 (NA1_5652115869)
New qualifying downloads this run: 15/2000 (NA1_5651712230)
New qualifying downloads this run: 16/2000 (NA1_5651395428)
New qualifying downloads this run: 17/2000 (NA1_5652008574)
New qualifying downloads this run: 18/2000 (NA1_5652933605)
New qualifying downloads this run: 19/2000 (NA1_5651436467)
New qualifying downloads this run: 20/2000 (NA1_5650199796)
New qualifying downloads this run: 21/2000 (NA1_5650135323)
New qualifying downloads this run: 22/2000 (NA1_5652877003)
New qualifying downloads this run: 23/2000 (NA1_5649894045)
New qualifying downloads this run: 24/2000 (NA1_5650552408)
New qualifying downloads this run: 25/2000 (NA1_5651057320)
New qualifying downloads this run: 26/2000 (NA1_5649989812)
New qualifying downloads this run: 27/2000 (NA1_5652547654)
New qualifying downloads this run: 28/2000 (NA1_5651241805)
New qualifying downloads this run: 29/2000 (NA1_5649959174)
New qualifying downloads this run: 30/2000 (NA1_5651407146)
New qualifying downloads this run: 31/2000 (NA1_5651839739)
New qualifying downloads this run: 32/2000 (NA1_5651514941)
New qualifying downloads this run: 33/2000 (NA1_5651312111)
New qualifying downloads this run: 34/2000 (NA1_5652860621)
New qualifying downloads this run: 35/2000 (NA1_5652414833)
New qualifying downloads this run: 36/2000 (NA1_5651423069)
New qualifying downloads this run: 37/2000 (NA1_5651363859)
New qualifying downloads this run: 38/2000 (NA1_5652564095)
New qualifying downloads this run: 39/2000 (NA1_5651243651)
New qualifying downloads this run: 40/2000 (NA1_5651556394)
New qualifying downloads this run: 41/2000 (NA1_5651961374)
New qualifying downloads this run: 42/2000 (NA1_5650364893)
New qualifying downloads this run: 43/2000 (NA1_5651249710)
New qualifying downloads this run: 44/2000 (NA1_5651316317)
New qualifying downloads this run: 45/2000 (NA1_5650842271)
New qualifying downloads this run: 46/2000 (NA1_5651858008)
New qualifying downloads this run: 47/2000 (NA1_5650879110)
New qualifying downloads this run: 48/2000 (NA1_5651160931)
New qualifying downloads this run: 49/2000 (NA1_5652544557)
New qualifying downloads this run: 50/2000 (NA1_5650441285)
New qualifying downloads this run: 51/2000 (NA1_5651867557)
New qualifying downloads this run: 52/2000 (NA1_5651779902)
New qualifying downloads this run: 53/2000 (NA1_5649984378)
New qualifying downloads this run: 54/2000 (NA1_5652121203)
New qualifying downloads this run: 55/2000 (NA1_5649574703)
New qualifying downloads this run: 56/2000 (NA1_5652400493)
New qualifying downloads this run: 57/2000 (NA1_5652431355)
New qualifying downloads this run: 58/2000 (NA1_5652178236)
New qualifying downloads this run: 59/2000 (NA1_5652801529)
New qualifying downloads this run: 60/2000 (NA1_5650602348)
New qualifying downloads this run: 61/2000 (NA1_5650069673)
New qualifying downloads this run: 62/2000 (NA1_5651124333)
New qualifying downloads this run: 63/2000 (NA1_5649912443)
New qualifying downloads this run: 64/2000 (NA1_5650014284)
New qualifying downloads this run: 65/2000 (NA1_5652277678)
New qualifying downloads this run: 66/2000 (NA1_5652748545)
New qualifying downloads this run: 67/2000 (NA1_5651387461)
New qualifying downloads this run: 68/2000 (NA1_5651578784)
New qualifying downloads this run: 69/2000 (NA1_5650331908)
New qualifying downloads this run: 70/2000 (NA1_5650630599)
New qualifying downloads this run: 71/2000 (NA1_5653074127)
New qualifying downloads this run: 72/2000 (NA1_5652064658)
New qualifying downloads this run: 73/2000 (NA1_5650803803)
New qualifying downloads this run: 74/2000 (NA1_5650784308)
New qualifying downloads this run: 75/2000 (NA1_5652048262)
New qualifying downloads this run: 76/2000 (NA1_5652498504)
New qualifying downloads this run: 77/2000 (NA1_5651786750)
New qualifying downloads this run: 78/2000 (NA1_5652476853)
New qualifying downloads this run: 79/2000 (NA1_5651147067)
New qualifying downloads this run: 80/2000 (NA1_5652903362)
New qualifying downloads this run: 81/2000 (NA1_5652941658)
New qualifying downloads this run: 82/2000 (NA1_5651963127)
New qualifying downloads this run: 83/2000 (NA1_5650953950)
New qualifying downloads this run: 84/2000 (NA1_5652206886)
New qualifying downloads this run: 85/2000 (NA1_5652367178)
New qualifying downloads this run: 86/2000 (NA1_5652916701)
New qualifying downloads this run: 87/2000 (NA1_5650816341)
New qualifying downloads this run: 88/2000 (NA1_5650641682)
New qualifying downloads this run: 89/2000 (NA1_5650583027)
New qualifying downloads this run: 90/2000 (NA1_5651426692)
New qualifying downloads this run: 91/2000 (NA1_5649574233)
New qualifying downloads this run: 92/2000 (NA1_5651357841)
New qualifying downloads this run: 93/2000 (NA1_5651849816)
New qualifying downloads this run: 94/2000 (NA1_5650652528)
New qualifying downloads this run: 95/2000 (NA1_5651864448)
New qualifying downloads this run: 96/2000 (NA1_5652986618)
New qualifying downloads this run: 97/2000 (NA1_5650990105)
New qualifying downloads this run: 98/2000 (NA1_5652578458)
New qualifying downloads this run: 99/2000 (NA1_5652467139)
New qualifying downloads this run: 100/2000 (NA1_5651393002)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 101/2000 (NA1_5651874436)
New qualifying downloads this run: 102/2000 (NA1_5650598189)
New qualifying downloads this run: 103/2000 (NA1_5652458713)
New qualifying downloads this run: 104/2000 (NA1_5650198111)
New qualifying downloads this run: 105/2000 (NA1_5652424407)
New qualifying downloads this run: 106/2000 (NA1_5652603237)
New qualifying downloads this run: 107/2000 (NA1_5652009747)
New qualifying downloads this run: 108/2000 (NA1_5649581266)
New qualifying downloads this run: 109/2000 (NA1_5651573847)
New qualifying downloads this run: 110/2000 (NA1_5651301263)
New qualifying downloads this run: 111/2000 (NA1_5652978960)
New qualifying downloads this run: 112/2000 (NA1_5652483004)
New qualifying downloads this run: 113/2000 (NA1_5649847848)
New qualifying downloads this run: 114/2000 (NA1_5652873700)
New qualifying downloads this run: 115/2000 (NA1_5651997090)
New qualifying downloads this run: 116/2000 (NA1_5650180178)
New qualifying downloads this run: 117/2000 (NA1_5649555531)
New qualifying downloads this run: 118/2000 (NA1_5651825298)
New qualifying downloads this run: 119/2000 (NA1_5651329833)
New qualifying downloads this run: 120/2000 (NA1_5653048188)
New qualifying downloads this run: 121/2000 (NA1_5652827369)
New qualifying downloads this run: 122/2000 (NA1_5652272593)
New qualifying downloads this run: 123/2000 (NA1_5650654892)
New qualifying downloads this run: 124/2000 (NA1_5651923414)
New qualifying downloads this run: 125/2000 (NA1_5650968383)
New qualifying downloads this run: 126/2000 (NA1_5651380183)
New qualifying downloads this run: 127/2000 (NA1_5651989163)
New qualifying downloads this run: 128/2000 (NA1_5652979199)
New qualifying downloads this run: 129/2000 (NA1_5652754696)
New qualifying downloads this run: 130/2000 (NA1_5650664722)
New qualifying downloads this run: 131/2000 (NA1_5652703437)
New qualifying downloads this run: 132/2000 (NA1_5653015677)
New qualifying downloads this run: 133/2000 (NA1_5649653650)
New qualifying downloads this run: 134/2000 (NA1_5651556068)
New qualifying downloads this run: 135/2000 (NA1_5651534669)
New qualifying downloads this run: 136/2000 (NA1_5649926258)
New qualifying downloads this run: 137/2000 (NA1_5651952946)
New qualifying downloads this run: 138/2000 (NA1_5650186527)
New qualifying downloads this run: 139/2000 (NA1_5650157991)
New qualifying downloads this run: 140/2000 (NA1_5651746166)
New qualifying downloads this run: 141/2000 (NA1_5650868409)
New qualifying downloads this run: 142/2000 (NA1_5651766860)
New qualifying downloads this run: 143/2000 (NA1_5649565118)
New qualifying downloads this run: 144/2000 (NA1_5652167112)
New qualifying downloads this run: 145/2000 (NA1_5649559613)
New qualifying downloads this run: 146/2000 (NA1_5651792967)
New qualifying downloads this run: 147/2000 (NA1_5650579515)
New qualifying downloads this run: 148/2000 (NA1_5651587542)
New qualifying downloads this run: 149/2000 (NA1_5652598331)
New qualifying downloads this run: 150/2000 (NA1_5650228960)
New qualifying downloads this run: 151/2000 (NA1_5649974240)
New qualifying downloads this run: 152/2000 (NA1_5653064315)
New qualifying downloads this run: 153/2000 (NA1_5650678472)
New qualifying downloads this run: 154/2000 (NA1_5652057890)
New qualifying downloads this run: 155/2000 (NA1_5649873683)
New qualifying downloads this run: 156/2000 (NA1_5651666292)
New qualifying downloads this run: 157/2000 (NA1_5652386448)
New qualifying downloads this run: 158/2000 (NA1_5650414455)
New qualifying downloads this run: 159/2000 (NA1_5650378809)
New qualifying downloads this run: 160/2000 (NA1_5652533132)
New qualifying downloads this run: 161/2000 (NA1_5651234720)
New qualifying downloads this run: 162/2000 (NA1_5651331464)
New qualifying downloads this run: 163/2000 (NA1_5650876200)
New qualifying downloads this run: 164/2000 (NA1_5650529112)
New qualifying downloads this run: 165/2000 (NA1_5651191926)
New qualifying downloads this run: 166/2000 (NA1_5652791688)
New qualifying downloads this run: 167/2000 (NA1_5652479164)
New qualifying downloads this run: 168/2000 (NA1_5650081098)
New qualifying downloads this run: 169/2000 (NA1_5651316408)
New qualifying downloads this run: 170/2000 (NA1_5649713684)
New qualifying downloads this run: 171/2000 (NA1_5650983723)
New qualifying downloads this run: 172/2000 (NA1_5652754850)
New qualifying downloads this run: 173/2000 (NA1_5649929305)
New qualifying downloads this run: 174/2000 (NA1_5652072416)
New qualifying downloads this run: 175/2000 (NA1_5650050795)
New qualifying downloads this run: 176/2000 (NA1_5650002065)
New qualifying downloads this run: 177/2000 (NA1_5651972965)
New qualifying downloads this run: 178/2000 (NA1_5650866012)
New qualifying downloads this run: 179/2000 (NA1_5651836343)
New qualifying downloads this run: 180/2000 (NA1_5650775441)
New qualifying downloads this run: 181/2000 (NA1_5652573238)
New qualifying downloads this run: 182/2000 (NA1_5652466923)
New qualifying downloads this run: 183/2000 (NA1_5650044406)
New qualifying downloads this run: 184/2000 (NA1_5650314427)
New qualifying downloads this run: 185/2000 (NA1_5649941426)
New qualifying downloads this run: 186/2000 (NA1_5652592295)
New qualifying downloads this run: 187/2000 (NA1_5650640115)
New qualifying downloads this run: 188/2000 (NA1_5652788507)
New qualifying downloads this run: 189/2000 (NA1_5651833227)
New qualifying downloads this run: 190/2000 (NA1_5652620645)
New qualifying downloads this run: 191/2000 (NA1_5652059133)
New qualifying downloads this run: 192/2000 (NA1_5650914069)
New qualifying downloads this run: 193/2000 (NA1_5651970738)
New qualifying downloads this run: 194/2000 (NA1_5652575772)
New qualifying downloads this run: 195/2000 (NA1_5651404526)
New qualifying downloads this run: 196/2000 (NA1_5652671007)
New qualifying downloads this run: 197/2000 (NA1_5651307067)
New qualifying downloads this run: 198/2000 (NA1_5652145985)
New qualifying downloads this run: 199/2000 (NA1_5651081393)
New qualifying downloads this run: 200/2000 (NA1_5650721078)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 201/2000 (NA1_5652866518)
New qualifying downloads this run: 202/2000 (NA1_5650814150)
New qualifying downloads this run: 203/2000 (NA1_5651212037)
New qualifying downloads this run: 204/2000 (NA1_5652434866)
New qualifying downloads this run: 205/2000 (NA1_5651881979)
New qualifying downloads this run: 206/2000 (NA1_5650807616)
New qualifying downloads this run: 207/2000 (NA1_5651890463)
New qualifying downloads this run: 208/2000 (NA1_5652866105)
New qualifying downloads this run: 209/2000 (NA1_5651057450)
New qualifying downloads this run: 210/2000 (NA1_5652241874)
New qualifying downloads this run: 211/2000 (NA1_5651182648)
New qualifying downloads this run: 212/2000 (NA1_5652088115)
New qualifying downloads this run: 213/2000 (NA1_5650856364)
New qualifying downloads this run: 214/2000 (NA1_5650363297)
New qualifying downloads this run: 215/2000 (NA1_5651891715)
New qualifying downloads this run: 216/2000 (NA1_5650138766)
New qualifying downloads this run: 217/2000 (NA1_5649682383)
New qualifying downloads this run: 218/2000 (NA1_5649554253)
New qualifying downloads this run: 219/2000 (NA1_5652423197)
New qualifying downloads this run: 220/2000 (NA1_5652390883)
New qualifying downloads this run: 221/2000 (NA1_5652862750)
New qualifying downloads this run: 222/2000 (NA1_5651643397)
New qualifying downloads this run: 223/2000 (NA1_5650199439)
New qualifying downloads this run: 224/2000 (NA1_5650091273)
New qualifying downloads this run: 225/2000 (NA1_5651331590)
New qualifying downloads this run: 226/2000 (NA1_5652392462)
New qualifying downloads this run: 227/2000 (NA1_5649968778)
New qualifying downloads this run: 228/2000 (NA1_5649567198)
New qualifying downloads this run: 229/2000 (NA1_5650933518)
New qualifying downloads this run: 230/2000 (NA1_5651654058)
New qualifying downloads this run: 231/2000 (NA1_5652487997)
New qualifying downloads this run: 232/2000 (NA1_5651868340)
New qualifying downloads this run: 233/2000 (NA1_5651159422)
New qualifying downloads this run: 234/2000 (NA1_5652549986)
New qualifying downloads this run: 235/2000 (NA1_5651292326)
New qualifying downloads this run: 236/2000 (NA1_5652957212)
New qualifying downloads this run: 237/2000 (NA1_5651182864)
New qualifying downloads this run: 238/2000 (NA1_5651121015)
New qualifying downloads this run: 239/2000 (NA1_5652961854)
New qualifying downloads this run: 240/2000 (NA1_5651527494)
New qualifying downloads this run: 241/2000 (NA1_5652768790)
New qualifying downloads this run: 242/2000 (NA1_5652676413)
New qualifying downloads this run: 243/2000 (NA1_5650655058)
New qualifying downloads this run: 244/2000 (NA1_5652477753)
New qualifying downloads this run: 245/2000 (NA1_5651316822)
New qualifying downloads this run: 246/2000 (NA1_5651127516)
New qualifying downloads this run: 247/2000 (NA1_5651995601)
New qualifying downloads this run: 248/2000 (NA1_5650781283)
New qualifying downloads this run: 249/2000 (NA1_5650837633)
New qualifying downloads this run: 250/2000 (NA1_5650813809)
New qualifying downloads this run: 251/2000 (NA1_5651364068)
New qualifying downloads this run: 252/2000 (NA1_5652000150)
New qualifying downloads this run: 253/2000 (NA1_5650356103)
New qualifying downloads this run: 254/2000 (NA1_5651781915)
New qualifying downloads this run: 255/2000 (NA1_5651305498)
New qualifying downloads this run: 256/2000 (NA1_5652386488)
New qualifying downloads this run: 257/2000 (NA1_5652964150)
New qualifying downloads this run: 258/2000 (NA1_5651347492)
New qualifying downloads this run: 259/2000 (NA1_5651884317)
New qualifying downloads this run: 260/2000 (NA1_5652997507)
New qualifying downloads this run: 261/2000 (NA1_5649531635)
New qualifying downloads this run: 262/2000 (NA1_5650588997)
New qualifying downloads this run: 263/2000 (NA1_5650650816)
New qualifying downloads this run: 264/2000 (NA1_5652577712)
New qualifying downloads this run: 265/2000 (NA1_5650345544)
New qualifying downloads this run: 266/2000 (NA1_5649869841)
New qualifying downloads this run: 267/2000 (NA1_5652877151)
New qualifying downloads this run: 268/2000 (NA1_5652033650)
New qualifying downloads this run: 269/2000 (NA1_5651960064)
New qualifying downloads this run: 270/2000 (NA1_5650366750)
New qualifying downloads this run: 271/2000 (NA1_5651142049)
New qualifying downloads this run: 272/2000 (NA1_5649975438)
New qualifying downloads this run: 273/2000 (NA1_5649957844)
New qualifying downloads this run: 274/2000 (NA1_5653056900)
New qualifying downloads this run: 275/2000 (NA1_5652878107)
New qualifying downloads this run: 276/2000 (NA1_5651606884)
New qualifying downloads this run: 277/2000 (NA1_5651212259)
New qualifying downloads this run: 278/2000 (NA1_5651007644)
New qualifying downloads this run: 279/2000 (NA1_5651068889)
New qualifying downloads this run: 280/2000 (NA1_5650935459)
New qualifying downloads this run: 281/2000 (NA1_5651100305)
New qualifying downloads this run: 282/2000 (NA1_5652291954)
New qualifying downloads this run: 283/2000 (NA1_5652690527)
New qualifying downloads this run: 284/2000 (NA1_5650183566)
New qualifying downloads this run: 285/2000 (NA1_5651410099)
New qualifying downloads this run: 286/2000 (NA1_5649538375)
New qualifying downloads this run: 287/2000 (NA1_5650184304)
New qualifying downloads this run: 288/2000 (NA1_5652447875)
New qualifying downloads this run: 289/2000 (NA1_5649501389)
New qualifying downloads this run: 290/2000 (NA1_5651983768)
New qualifying downloads this run: 291/2000 (NA1_5652821431)
New qualifying downloads this run: 292/2000 (NA1_5649913397)
New qualifying downloads this run: 293/2000 (NA1_5649594050)
New qualifying downloads this run: 294/2000 (NA1_5650194172)
New qualifying downloads this run: 295/2000 (NA1_5649567611)
New qualifying downloads this run: 296/2000 (NA1_5652562139)
New qualifying downloads this run: 297/2000 (NA1_5652131665)
New qualifying downloads this run: 298/2000 (NA1_5650984976)
New qualifying downloads this run: 299/2000 (NA1_5649624387)
New qualifying downloads this run: 300/2000 (NA1_5651954629)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 301/2000 (NA1_5653024640)
New qualifying downloads this run: 302/2000 (NA1_5651323111)
New qualifying downloads this run: 303/2000 (NA1_5651923966)
New qualifying downloads this run: 304/2000 (NA1_5652560828)
New qualifying downloads this run: 305/2000 (NA1_5652319674)
New qualifying downloads this run: 306/2000 (NA1_5652890970)
New qualifying downloads this run: 307/2000 (NA1_5652465130)
New qualifying downloads this run: 308/2000 (NA1_5652114557)
New qualifying downloads this run: 309/2000 (NA1_5649530152)
New qualifying downloads this run: 310/2000 (NA1_5651179045)
New qualifying downloads this run: 311/2000 (NA1_5650703730)
New qualifying downloads this run: 312/2000 (NA1_5652552196)
New qualifying downloads this run: 313/2000 (NA1_5652984621)
New qualifying downloads this run: 314/2000 (NA1_5652855799)
New qualifying downloads this run: 315/2000 (NA1_5650497006)
New qualifying downloads this run: 316/2000 (NA1_5651266401)
New qualifying downloads this run: 317/2000 (NA1_5650103751)
New qualifying downloads this run: 318/2000 (NA1_5652961989)
New qualifying downloads this run: 319/2000 (NA1_5650532704)
New qualifying downloads this run: 320/2000 (NA1_5652024701)
New qualifying downloads this run: 321/2000 (NA1_5651564485)
New qualifying downloads this run: 322/2000 (NA1_5653060914)
New qualifying downloads this run: 323/2000 (NA1_5651072686)
New qualifying downloads this run: 324/2000 (NA1_5650064159)
New qualifying downloads this run: 325/2000 (NA1_5650482796)
New qualifying downloads this run: 326/2000 (NA1_5650735900)

## Build pre-game OTP rates and analysis outputs

The collection first identifies patch-16.19 matches with a reliable same-role opponent. It then retrieves each sampled player's ordered Ranked Solo/Duo history through at least 50 games before their earliest observed match. The previous 50 games may come from an earlier patch. Their match payloads are cached in the same directory, but only patch-16.19 matches become analysis observations. `champion_share` is the proportion of these 50 **earlier** games played on the champion used in the observation; it never includes the observation or future games. An exact 50-game window is required.

In [31]:
# Find all qualifying patch-16.19 matches already downloaded
coverage, downloaded_match_ids = otp.cached_patch_history_coverage(
    new_only_index,
    RAW_MATCH_DIR,
    TARGET_PATCH,
    MATCHES_PER_PLAYER,
)

print("Downloaded qualifying matches:", len(downloaded_match_ids))

# Randomly keep exactly 1,000 of those downloaded matches
analysis_1000_ids = set(
    pd.Series(sorted(downloaded_match_ids))
    .sample(n=1000, random_state=MATCH_SELECTION_SEED)
)

# Keep player-match relationships only for those 1,000 matches
analysis_1000_index = new_only_index[
    new_only_index["match_id"].isin(analysis_1000_ids)
].copy()

print("Analysis matches:", analysis_1000_index["match_id"].nunique())
print("Player-match index rows:", len(analysis_1000_index))

Downloaded qualifying matches: 2785
Analysis matches: 1000
Player-match index rows: 4852

In [32]:
patch_candidates, unreadable_files = otp.build_otp_dataset(
    analysis_1000_index,
    RAW_MATCH_DIR,
    TARGET_PATCH,
)

print("Analysis matches:", patch_candidates["match_id"].nunique())
print("Player-game observations:", len(patch_candidates))
print("Unique players:", patch_candidates["puuid"].nunique())
print("Unreadable files:", unreadable_files)

Analysis matches: 999
Player-game observations: 4851
Unique players: 1392
Unreadable files: 0

In [33]:
# Replace any sampled matches that produced no usable observation
usable_ids = set(patch_candidates["match_id"].unique())
missing_count = 1000 - len(usable_ids)

print("Usable so far:", len(usable_ids))
print("Replacements needed:", missing_count)

if missing_count > 0:
    replacement_pool = list(
        set(downloaded_match_ids)
        - analysis_1000_ids
        - usable_ids
    )

    replacement_ids = set(
        pd.Series(sorted(replacement_pool))
        .sample(n=missing_count, random_state=MATCH_SELECTION_SEED + 1)
    )

    analysis_1000_ids = analysis_1000_ids | replacement_ids

    analysis_1000_index = new_only_index[
        new_only_index["match_id"].isin(analysis_1000_ids)
    ].copy()

    patch_candidates, unreadable_files = otp.build_otp_dataset(
        analysis_1000_index,
        RAW_MATCH_DIR,
        TARGET_PATCH,
    )

print("Usable analysis matches:", patch_candidates["match_id"].nunique())
print("Player-game observations:", len(patch_candidates))
print("Unique players:", patch_candidates["puuid"].nunique())

Usable so far: 999
Replacements needed: 1
Usable analysis matches: 1000
Player-game observations: 4853
Unique players: 1392

In [34]:
pregame_history_index = otp.load_pregame_history_index(PROCESSED_DIR)

In [35]:
# Continue using our CURRENT 1,000-match patch_candidates.
# Do NOT rebuild patch_candidates from player_match_index.

if RUN_API_COLLECTION:
    print(
        f"Finding the previous {PRIOR_GAMES} Solo/Duo games for "
        f"{patch_candidates['puuid'].nunique():,} sampled players. "
        "History ID requests and missing match downloads can take many hours."
    )

    pregame_history_index = otp.append_pregame_histories(
        pregame_history_index,
        patch_candidates,
        HEADERS,
        PROCESSED_DIR,
        prior_games=PRIOR_GAMES,
        page_size=MATCHES_PER_PLAYER,
    )

required_prior_ids = otp.pregame_required_ids(
    patch_candidates,
    pregame_history_index,
    prior_games=PRIOR_GAMES,
)

missing_prior_ids = [
    match_id
    for match_id in required_prior_ids
    if not (RAW_MATCH_DIR / f"{match_id}.json").exists()
]

print(f"Unique prior match payloads needed: {len(required_prior_ids):,}")
print(f"Currently missing: {len(missing_prior_ids):,}")

if RUN_API_COLLECTION and missing_prior_ids:
    pregame_download_index = (
        pregame_history_index.loc[
            pregame_history_index["match_id"].isin(required_prior_ids),
            ["puuid", "match_id"],
        ]
        .merge(
            seed_players,
            on="puuid",
            how="left",
            validate="many_to_one",
        )
    )

    pregame_download_index["seed_tier"] = (
        pregame_download_index["seed_tier"].fillna("unknown")
    )

    otp.download_missing_matches(
        pregame_download_index,
        RAW_MATCH_DIR,
        HEADERS,
        max_new_downloads=len(missing_prior_ids),
        progress_every=100,
    )

with_pregame_rate = otp.attach_pregame_usage(
    patch_candidates,
    pregame_history_index,
    RAW_MATCH_DIR,
    prior_games=PRIOR_GAMES,
)

otp_matches = with_pregame_rate.loc[
    with_pregame_rate["champion_share"].notna()
].copy()

print(
    f"Patch player-games before pre-game history check: "
    f"{len(patch_candidates):,}"
)
print(
    f"Player-games with {PRIOR_GAMES} complete earlier games: "
    f"{len(otp_matches):,}"
)
print(
    f"Player-games excluded for short/incomplete history: "
    f"{len(patch_candidates) - len(otp_matches):,}"
)

if otp_matches.empty:
    raise RuntimeError(
        "No observations have a complete previous-50 history yet."
    )

assert otp_matches["player_games"].eq(PRIOR_GAMES).all()

otp.save_otp_dataset(
    otp_matches,
    PROCESSED_DIR,
    TARGET_PATCH,
)

unique_matchups = otp.build_unique_matchups(otp_matches)

otp.save_unique_matchups(
    unique_matchups,
    PROCESSED_DIR,
    TARGET_PATCH,
)

print("DONE")
print("Final OTP observations:", len(otp_matches))
print("Unique matchups:", len(unique_matchups))

Finding the previous 50 Solo/Duo games for 1,392 sampled players. History ID requests and missing match downloads can take many hours.
Pre-game histories checkpointed: 25/1,392 players refreshed
Pre-game histories checkpointed: 50/1,392 players refreshed
Unique prior match payloads needed: 45,101
Currently missing: 40,138
Cached matches found: 5,494
Match IDs requested: 45,101
New matches remaining: 40,138
Rate limited; waiting 94 seconds.
New qualifying downloads this run: 100/40138 (NA1_5644490321)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 200/40138 (NA1_5644458084)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 300/40138 (NA1_5639455569)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 400/40138 (NA1_5640478589)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 500/40138 (NA1_5645762455)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 600/40138 (NA1_5642374771)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 700/40138 (NA1_5649607286)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 800/40138 (NA1_5648290583)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 900/40138 (NA1_5649110047)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 1000/40138 (NA1_5635389280)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 1100/40138 (NA1_5637370017)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 1200/40138 (NA1_5642976093)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 1300/40138 (NA1_5648174212)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 1400/40138 (NA1_5646738127)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 1500/40138 (NA1_5646098813)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 1600/40138 (NA1_5649422678)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 1700/40138 (NA1_5648429650)
Rate limited; waiting 84 seconds.
New qualifying downloads this run: 1800/40138 (NA1_5652872490)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 1900/40138 (NA1_5651215741)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 2000/40138 (NA1_5633840030)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 2100/40138 (NA1_5643841647)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 2200/40138 (NA1_5652190484)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 2300/40138 (NA1_5648535678)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 2400/40138 (NA1_5624833298)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 2500/40138 (NA1_5644359677)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 2600/40138 (NA1_5648930240)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 2700/40138 (NA1_5643949310)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 2800/40138 (NA1_5645616639)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 2900/40138 (NA1_5632395001)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 3000/40138 (NA1_5650270714)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 3100/40138 (NA1_5648592646)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 3200/40138 (NA1_5644982390)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 3300/40138 (NA1_5650060354)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 3400/40138 (NA1_5643751106)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 3500/40138 (NA1_5637330749)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 3600/40138 (NA1_5635486909)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 3700/40138 (NA1_5644090558)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 3800/40138 (NA1_5634955223)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 3900/40138 (NA1_5637495782)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 4000/40138 (NA1_5645883636)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 4100/40138 (NA1_5648240081)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 4200/40138 (NA1_5626594070)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 4300/40138 (NA1_5651064655)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 4400/40138 (NA1_5638623302)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 4500/40138 (NA1_5649892390)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 4600/40138 (NA1_5626737675)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 4700/40138 (NA1_5643345554)
Rate limited; waiting 83 seconds.
New qualifying downloads this run: 4800/40138 (NA1_5647360998)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 4900/40138 (NA1_5648199619)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 5000/40138 (NA1_5644058302)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 5100/40138 (NA1_5643603116)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 5200/40138 (NA1_5652496748)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 5300/40138 (NA1_5646000535)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 5400/40138 (NA1_5623331239)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 5500/40138 (NA1_5647577480)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 5600/40138 (NA1_5643354700)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 5700/40138 (NA1_5633164644)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 5800/40138 (NA1_5652156843)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 5900/40138 (NA1_5641409127)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 6000/40138 (NA1_5650477768)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 6100/40138 (NA1_5643055614)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 6200/40138 (NA1_5650825885)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 6300/40138 (NA1_5644253231)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 6400/40138 (NA1_5644887097)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 6500/40138 (NA1_5649087232)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 6600/40138 (NA1_5642004611)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 6700/40138 (NA1_5652995187)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 6800/40138 (NA1_5651554995)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 6900/40138 (NA1_5643928511)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 7000/40138 (NA1_5641953180)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 7100/40138 (NA1_5636784730)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 7200/40138 (NA1_5634195434)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 7300/40138 (NA1_5652428053)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 7400/40138 (NA1_5641131562)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 7500/40138 (NA1_5643076731)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 7600/40138 (NA1_5647798665)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 7700/40138 (NA1_5636008873)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 7800/40138 (NA1_5623457078)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 7900/40138 (NA1_5651780359)
Rate limited; waiting 84 seconds.
New qualifying downloads this run: 8000/40138 (NA1_5647543601)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 8100/40138 (NA1_5626975998)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 8200/40138 (NA1_5640214480)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 8300/40138 (NA1_5641375980)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 8400/40138 (NA1_5628085111)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 8500/40138 (NA1_5650002808)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 8600/40138 (NA1_5618152698)
Match skipped (NA1_5651630046): 504 Server Error: Gateway Timeout for url: https://americas.api.riotgames.com/lol/match/v5/matches/NA1_5651630046
Match skipped (NA1_5647723952): 504 Server Error: Gateway Timeout for url: https://americas.api.riotgames.com/lol/match/v5/matches/NA1_5647723952
Rate limited; waiting 83 seconds.
New qualifying downloads this run: 8700/40138 (NA1_5624060818)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 8800/40138 (NA1_5636994783)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 8900/40138 (NA1_5650764584)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 9000/40138 (NA1_5640139754)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 9100/40138 (NA1_5643398386)
Rate limited; waiting 78 seconds.
New qualifying downloads this run: 9200/40138 (NA1_5647619474)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 9300/40138 (NA1_5646347683)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 9400/40138 (NA1_5627106002)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 9500/40138 (NA1_5644262314)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 9600/40138 (NA1_5651134121)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 9700/40138 (NA1_5648253714)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 9800/40138 (NA1_5650141500)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 9900/40138 (NA1_5646103034)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 10000/40138 (NA1_5647688354)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 10100/40138 (NA1_5650862153)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 10200/40138 (NA1_5634723973)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 10300/40138 (NA1_5631411666)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 10400/40138 (NA1_5646914692)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 10500/40138 (NA1_5637313022)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 10600/40138 (NA1_5632572210)
Rate limited; waiting 82 seconds.
New qualifying downloads this run: 10700/40138 (NA1_5642579248)
Rate limited; waiting 82 seconds.
New qualifying downloads this run: 10800/40138 (NA1_5643444123)
Rate limited; waiting 80 seconds.
New qualifying downloads this run: 10900/40138 (NA1_5630360710)
Rate limited; waiting 84 seconds.
New qualifying downloads this run: 11000/40138 (NA1_5652107781)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 11100/40138 (NA1_5628831054)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 11200/40138 (NA1_5635630264)
Rate limited; waiting 83 seconds.
New qualifying downloads this run: 11300/40138 (NA1_5643150039)
Rate limited; waiting 84 seconds.
New qualifying downloads this run: 11400/40138 (NA1_5649348180)
Rate limited; waiting 83 seconds.
New qualifying downloads this run: 11500/40138 (NA1_5636773083)
Rate limited; waiting 81 seconds.
New qualifying downloads this run: 11600/40138 (NA1_5644818764)
Rate limited; waiting 78 seconds.
New qualifying downloads this run: 11700/40138 (NA1_5642864977)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 11800/40138 (NA1_5624625905)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 11900/40138 (NA1_5641466899)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 12000/40138 (NA1_5651188111)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 12100/40138 (NA1_5628576974)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 12200/40138 (NA1_5641279970)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 12300/40138 (NA1_5649564532)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 12400/40138 (NA1_5650657263)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 12500/40138 (NA1_5646903460)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 12600/40138 (NA1_5649258218)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 12700/40138 (NA1_5624686259)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 12800/40138 (NA1_5647948909)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 12900/40138 (NA1_5626350651)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 13000/40138 (NA1_5642049420)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 13100/40138 (NA1_5647874038)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 13200/40138 (NA1_5648464115)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 13300/40138 (NA1_5629762458)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 13400/40138 (NA1_5648632924)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 13500/40138 (NA1_5646396030)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 13600/40138 (NA1_5634541323)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 13700/40138 (NA1_5629458719)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 13800/40138 (NA1_5651043840)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 13900/40138 (NA1_5643289024)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 14000/40138 (NA1_5637258229)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 14100/40138 (NA1_5637753840)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 14200/40138 (NA1_5634575635)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 14300/40138 (NA1_5628933311)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 14400/40138 (NA1_5636788058)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 14500/40138 (NA1_5633748160)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 14600/40138 (NA1_5647397592)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 14700/40138 (NA1_5651633366)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 14800/40138 (NA1_5642727422)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 14900/40138 (NA1_5645076400)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 15000/40138 (NA1_5645709626)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 15100/40138 (NA1_5643982064)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 15200/40138 (NA1_5639938968)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 15300/40138 (NA1_5633131433)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 15400/40138 (NA1_5648109400)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 15500/40138 (NA1_5618586275)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 15600/40138 (NA1_5651033719)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 15700/40138 (NA1_5623100595)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 15800/40138 (NA1_5645837563)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 15900/40138 (NA1_5644741156)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 16000/40138 (NA1_5643013412)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 16100/40138 (NA1_5649263064)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 16200/40138 (NA1_5648412416)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 16300/40138 (NA1_5624106955)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 16400/40138 (NA1_5650606290)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 16500/40138 (NA1_5637094919)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 16600/40138 (NA1_5628594591)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 16700/40138 (NA1_5647904699)
Rate limited; waiting 84 seconds.
New qualifying downloads this run: 16800/40138 (NA1_5645913101)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 16900/40138 (NA1_5647613037)
Rate limited; waiting 85 seconds.
New qualifying downloads this run: 17000/40138 (NA1_5649465321)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 17100/40138 (NA1_5647612621)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 17200/40138 (NA1_5648271520)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 17300/40138 (NA1_5640903958)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 17400/40138 (NA1_5650748834)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 17500/40138 (NA1_5647555591)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 17600/40138 (NA1_5646674993)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 17700/40138 (NA1_5644065571)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 17800/40138 (NA1_5651018495)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 17900/40138 (NA1_5649201898)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 18000/40138 (NA1_5638945896)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 18100/40138 (NA1_5628897197)
Rate limited; waiting 86 seconds.
New qualifying downloads this run: 18200/40138 (NA1_5651173223)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 18300/40138 (NA1_5647050956)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 18400/40138 (NA1_5269275875)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 18500/40138 (NA1_5638722191)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 18600/40138 (NA1_5644169437)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 18700/40138 (NA1_5643319031)
Rate limited; waiting 83 seconds.
New qualifying downloads this run: 18800/40138 (NA1_5647638632)
Match skipped (NA1_5632757235): HTTPSConnectionPool(host='americas.api.riotgames.com', port=443): Read timed out. (read timeout=30)
New qualifying downloads this run: 18900/40138 (NA1_5652570670)
Rate limited; waiting 87 seconds.
New qualifying downloads this run: 19000/40138 (NA1_5643894613)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 19100/40138 (NA1_5637923364)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 19200/40138 (NA1_5636526346)
Rate limited; waiting 88 seconds.
New qualifying downloads this run: 19300/40138 (NA1_5644993260)
Rate limited; waiting 84 seconds.
New qualifying downloads this run: 19400/40138 (NA1_5644244514)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 19500/40138 (NA1_5649407107)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 19600/40138 (NA1_5648818802)
Rate limited; waiting 89 seconds.
New qualifying downloads this run: 19700/40138 (NA1_5647376881)

## Inspection summary and player-history coverage

The patch-cache coverage table compares IDs returned since `PATCH_START_TIME` with cached patch payloads. It describes the patch sample. The pre-game check above separately reports observations retained with **50 complete earlier games**, which is the history requirement for `champion_share`. `player_games` is 50 for every saved observation.

In [37]:
tier_rows = otp_matches['seed_tier'].value_counts()
history_coverage, cached_patch_ids = otp.cached_patch_history_coverage(
    analysis_1000_index, RAW_MATCH_DIR, TARGET_PATCH, MATCHES_PER_PLAYER
)
cached_raw_matches = len(list(RAW_MATCH_DIR.glob("*.json")))
print(f'All cached raw JSON files: {cached_raw_matches:,}')
print(f'Cached indexed {TARGET_PATCH} Solo/Duo matches: {len(cached_patch_ids):,}')
print(f'Analysis-ready player-game rows: {len(otp_matches):,}')
print(f"Unique analysis matches: {otp_matches['match_id'].nunique():,}")
print(f"Unique sampled players: {otp_matches['puuid'].nunique():,}")
print(f"Master rows: {tier_rows.get('master', 0):,}")
print(f"Grandmaster rows: {tier_rows.get('grandmaster', 0):,}")
print(f"Challenger rows: {tier_rows.get('challenger', 0):,}")
print(f'Unique lane/champion/opponent combinations: {len(unique_matchups):,}')

if not history_coverage.empty:
    print(f'Indexed players with <80% cached usable patch-game coverage: '
          f"{(history_coverage['indexed_cache_coverage'] < 0.80).sum():,}/{len(history_coverage):,}")
    print(f'Indexed players with at least {MATCHES_PER_PLAYER} patch IDs (multiple-page histories): '
          f"{history_coverage['at_or_above_page_size'].sum():,}")
    display(history_coverage[
        ['indexed_since_start', 'cached_usable_patch_games', 'indexed_cache_coverage']
    ].describe(percentiles=[.10, .50, .90]))

display(otp_matches.head(20))
display(otp_matches.shape)
display(otp_matches.dtypes)

All cached raw JSON files: 45,629
Cached indexed 16.19 Solo/Duo matches: 1,001
Analysis-ready player-game rows: 4,836
Unique analysis matches: 1,000
Unique sampled players: 1,387
Master rows: 1,329
Grandmaster rows: 2,123
Challenger rows: 1,384
Unique lane/champion/opponent combinations: 3,455
Indexed players with <80% cached usable patch-game coverage: 0/1,392
Indexed players with at least 100 patch IDs (multiple-page histories): 0

       indexed_since_start  cached_usable_patch_games  indexed_cache_coverage
count          1392.000000                1392.000000                  1392.0
mean              3.487069                   3.487069                     1.0
std               3.557252                   3.557252                     0.0
min               1.000000                   1.000000                     1.0
10%               1.000000                   1.000000                     1.0
50%               2.000000                   2.000000                     1.0
90%               8.000000                   8.000000                     1.0
max              31.000000                  31.000000                     1.0

,match_id,puuid,seed_tier,patch,side,lane,champion,opponent_champion,opponent_puuid,win,game_duration,game_start_timestamp,champion_games,player_games,champion_share,otp_measure
0,NA1_5649511668,3gNdz4Q0umzJCWX0_Ao1DlXIig2vMov53d7ltMh3PIAjnf...,challenger,16.19,red,mid,TwistedFate,AurelionSol,By3WaYwajWV2YnZ6W4Vb1arXlLc_4gAOoKpZHGvI6t98Sc...,True,2299,1790462373131,18,50,0.36,previous_50_ranked_solo
1,NA1_5649511668,By3WaYwajWV2YnZ6W4Vb1arXlLc_4gAOoKpZHGvI6t98Sc...,grandmaster,16.19,blue,mid,AurelionSol,TwistedFate,3gNdz4Q0umzJCWX0_Ao1DlXIig2vMov53d7ltMh3PIAjnf...,False,2299,1790462373131,11,50,0.22,previous_50_ranked_solo
2,NA1_5649511668,GpD59_ThmLRGDxXIAZcaNEvOvILQxC1bZS7sXZJcjoCGai...,master,16.19,red,top,Illaoi,Kled,BuuVyBG7dY4gVWws1rO-binGa9PdcinYv7ZgWUn39LdM-9...,True,2299,1790462373131,47,50,0.94,previous_50_ranked_solo
3,NA1_5649511668,LDk1guhzOXvgZh6wXiI1dEPrk-rFAUBvB1A_tzraBbl1ib...,grandmaster,16.19,blue,adc,Syndra,Lux,WPnzp5a3IFXaFDiMC6xckon0yjPuCnVh8bnvNM0j8M57TA...,False,2299,1790462373131,31,50,0.62,previous_50_ranked_solo
4,NA1_5649511668,Yb_izYdkTe1ekL_67OYEQ__WaInRF-CSqp5uYlpsFbT8zM...,grandmaster,16.19,red,jungle,LeeSin,RekSai,2-GsGYJnr1_9Yqh0_Am0TEvjn-spPerzWt6mJAvMXsIqlg...,True,2299,1790462373131,12,50,0.24,previous_50_ranked_solo
5,NA1_5649518343,01Zk5sPHG9uIxwC31dEJjlW01bYrwdPOLHLfxjKOcE7VU0...,grandmaster,16.19,blue,mid,Ahri,Yasuo,DH0CSNhcxQGFq0kO7B92C4ZER1M-Hc4cQmWSMP5IGv2NL9...,False,1607,1790462544537,4,50,0.08,previous_50_ranked_solo
6,NA1_5649518343,5nuo3sQ1Z6NbPZNES3MaCcLCXAbDaqY-rFDXaP0o1ARL5a...,master,16.19,blue,jungle,Chogath,Shyvana,5UihiAolbsILCEbBIs4O41lifAw1DcmilI8hfmRtUz5hhc...,False,1607,1790462544537,0,50,0.0,previous_50_ranked_solo
7,NA1_5649518343,N-1A5MFyjubjp8TX2meDQhv4TEGCl_PRBTZt91SiDOxi7b...,grandmaster,16.19,red,adc,Zeri,Aphelios,NetObvmsioX5Aws_mqWKVFavbptcZ3Y-UHG-wYbPyMwpEJ...,True,1607,1790462544537,0,50,0.0,previous_50_ranked_solo
8,NA1_5649518343,kn7sNTxSQJxaPPl-lNQl14MmvY17cVRjCKZjpJE7P67JL1...,grandmaster,16.19,blue,support,Nautilus,Thresh,9ZM4CwkfrzSQDGGmpyY82SZNkYsaW4_OoRZYR1iIsNc_46...,False,1607,1790462544537,1,50,0.02,previous_50_ranked_solo
9,NA1_5649523357,-Tl4wA5vhyR8bbUmhIkolZDeYgoBHOg_JUwEyHxYH95Zl4...,master,16.19,blue,top,Riven,Kled,KC-A5oZ81Qm27hSJW-PK_TYLiaKlJqFny1dd2KLrOE0pkr...,False,2203,1790463189349,17,50,0.34,previous_50_ranked_solo
10,NA1_5649523357,H1yFGuksVjJZLiE4rGmMndiGjrKp6HjunnwWkfPRAnqi4n...,master,16.19,red,mid,Zoe,Lux,SvO_dXxk6OL0GiZOCr_NnYuVcOZdL4_Vo4euQ5Nu7fdQqC...,True,2203,1790463189349,3,50,0.06,previous_50_ranked_solo
11,NA1_5649523357,SvO_dXxk6OL0GiZOCr_NnYuVcOZdL4_Vo4euQ5Nu7fdQqC...,master,16.19,blue,mid,Lux,Zoe,H1yFGuksVjJZLiE4rGmMndiGjrKp6HjunnwWkfPRAnqi4n...,False,2203,1790463189349,15,50,0.3,previous_50_ranked_solo
12,NA1_5649531818,-chCHGFoZ9p2us9jmPtpeBYqV_MuhvmV7pOl_lqpqoc-Gs...,master,16.19,blue,adc,Draven,Veigar,q3OUQ3u3Lxnmc-ufylnjhf7HzomIyDEMi-goV1kdW8C5c7...,True,1968,1790463288826,29,50,0.58,previous_50_ranked_solo
13,NA1_5649531818,36BcRu3jTjfHhgMHmfBkCkt9U-mFPvUg6o2gJKD95Zv8Ws...,challenger,16.19,blue,jungle,Jayce,LeeSin,5oKgZxE8B7FUs_SPgbHTKYi8oPiN_qkxcSmkFebY3LquDW...,True,1968,1790463288826,3,50,0.06,previous_50_ranked_solo
14,NA1_5649531818,4M8P67n-zyHLB5i0ZDjxbxYMkVM6cFA0ZAJdmHkvZTzulG...,challenger,16.19,blue,top,Vayne,Ambessa,ELbPv-oVuEDE3z6dXsgKUt5AXtdCDBIsVttO_c8U9Jtgvi...,True,1968,1790463288826,2,50,0.04,previous_50_ranked_solo
15,NA1_5649531818,5oKgZxE8B7FUs_SPgbHTKYi8oPiN_qkxcSmkFebY3LquDW...,grandmaster,16.19,red,jungle,LeeSin,Jayce,36BcRu3jTjfHhgMHmfBkCkt9U-mFPvUg6o2gJKD95Zv8Ws...,False,1968,1790463288826,16,50,0.32,previous_50_ranked_solo
16,NA1_5649531818,C9lHeXDpchI1K4XHUi44JcJmc60xczbkMwN_hfc0zQ5xnH...,challenger,16.19,red,support,Nautilus,Blitzcrank,CTBfUvZ7f3_1oxBzvdgrVciP5wUqwlzag4oL_XcbnX2jDH...,False,1968,1790463288826,10,50,0.2,previous_50_ranked_solo
17,NA1_5649531818,CTBfUvZ7f3_1oxBzvdgrVciP5wUqwlzag4oL_XcbnX2jDH...,challenger,16.19,blue,support,Blitzcrank,Nautilus,C9lHeXDpchI1K4XHUi44JcJmc60xczbkMwN_hfc0zQ5xnH...,True,1968,1790463288826,0,50,0.0,previous_50_ranked_solo
18,NA1_5649531818,ELbPv-oVuEDE3z6dXsgKUt5AXtdCDBIsVttO_c8U9Jtgvi...,challenger,16.19,red,top,Ambessa,Vayne,4M8P67n-zyHLB5i0ZDjxbxYMkVM6cFA0ZAJdmHkvZTzulG...,False,1968,1790463288826,0,50,0.0,previous_50_ranked_solo
19,NA1_5649531818,Ey2SlBp-qz8VGESS56zbY0F10dJl8qUWnc0Q535LRxxSqp...,grandmaster,16.19,red,mid,Fizz,Zilean,d02emArdk7kw9_3PuhJ2QdofcTacpEwoSltxx6PkpxiENC...,False,1968,1790463288826,38,50,0.76,previous_50_ranked_solo

(4836, 16)

match_id                 object
puuid                    object
seed_tier                object
patch                    object
side                     object
lane                     object
champion                 object
opponent_champion        object
opponent_puuid           object
win                        bool
game_duration             int64
game_start_timestamp      int64
champion_games            Int64
player_games              Int64
champion_share          Float64
otp_measure              object
dtype: object